// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/phemmer/go-pulsar-state/bookkeeper/proto/common"
	stream "github.com/phemmer/go-pulsar-state/bookkeeper/proto/stream"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_SUCCESS StatusCode = 0
	StatusCode_FAILURE StatusCode = 1
	// 4xx: client errors
	StatusCode_BAD_REQUEST StatusCode = 400
	StatusCode_ILLEGAL_OP  StatusCode = 403
	// 5xx: server errors
	StatusCode_INTERNAL_SERVER_ERROR StatusCode = 500
	StatusCode_NOT_IMPLEMENTED       StatusCode = 501
	// 6xx: unexpected
	StatusCode_UNEXPECTED StatusCode = 600
	// 9xx: revisions, versions
	StatusCode_BAD_VERSION  StatusCode = 900
	StatusCode_BAD_REVISION StatusCode = 901
	// 20xx: Namespace Related
	StatusCode_INVALID_NAMESPACE_NAME StatusCode = 2000
	StatusCode_NAMESPACE_EXISTS       StatusCode = 2001
	StatusCode_NAMESPACE_NOT_FOUND    StatusCode = 2002
	// 21xx: Stream Related
	StatusCode_INVALID_STREAM_NAME         StatusCode = 2100
	StatusCode_STREAM_EXISTS               StatusCode = 2101
	StatusCode_STREAM_NOT_FOUND            StatusCode = 2102
	StatusCode_INVALID_STREAMSNAPSHOT_NAME StatusCode = 2103
	StatusCode_STREAMSNAPSHOT_EXISTS       StatusCode = 2104
	StatusCode_STREAMSNAPSHOT_NOT_FOUND    StatusCode = 2105
	// 3xxx: GROUP related
	StatusCode_WRONG_GROUP_LOCATION StatusCode = 3000
	StatusCode_INVALID_GROUP_ID     StatusCode = 3001
	StatusCode_GROUP_EXISTS         StatusCode = 3002
	StatusCode_GROUP_NOT_FOUND      StatusCode = 3003
	StatusCode_STALE_GROUP_INFO     StatusCode = 3004
	// 6xxx: Table related
	StatusCode_INVALID_KEY   StatusCode = 6000
	StatusCode_KEY_EXISTS    StatusCode = 6001
	StatusCode_KEY_NOT_FOUND StatusCode = 6002
)

var StatusCode_name = map[int32]string{
	0:    "SUCCESS",
	1:    "FAILURE",
	400:  "BAD_REQUEST",
	403:  "ILLEGAL_OP",
	500:  "INTERNAL_SERVER_ERROR",
	501:  "NOT_IMPLEMENTED",
	600:  "UNEXPECTED",
	900:  "BAD_VERSION",
	901:  "BAD_REVISION",
	2000: "INVALID_NAMESPACE_NAME",
	2001: "NAMESPACE_EXISTS",
	2002: "NAMESPACE_NOT_FOUND",
	2100: "INVALID_STREAM_NAME",
	2101: "STREAM_EXISTS",
	2102: "STREAM_NOT_FOUND",
	2103: "INVALID_STREAMSNAPSHOT_NAME",
	2104: "STREAMSNAPSHOT_EXISTS",
	2105: "STREAMSNAPSHOT_NOT_FOUND",
	3000: "WRONG_GROUP_LOCATION",
	3001: "INVALID_GROUP_ID",
	3002: "GROUP_EXISTS",
	3003: "GROUP_NOT_FOUND",
	3004: "STALE_GROUP_INFO",
	6000: "INVALID_KEY",
	6001: "KEY_EXISTS",
	6002: "KEY_NOT_FOUND",
}

var StatusCode_value = map[string]int32{
	"SUCCESS":                     0,
	"FAILURE":                     1,
	"BAD_REQUEST":                 400,
	"ILLEGAL_OP":                  403,
	"INTERNAL_SERVER_ERROR":       500,
	"NOT_IMPLEMENTED":             501,
	"UNEXPECTED":                  600,
	"BAD_VERSION":                 900,
	"BAD_REVISION":                901,
	"INVALID_NAMESPACE_NAME":      2000,
	"NAMESPACE_EXISTS":            2001,
	"NAMESPACE_NOT_FOUND":         2002,
	"INVALID_STREAM_NAME":         2100,
	"STREAM_EXISTS":               2101,
	"STREAM_NOT_FOUND":            2102,
	"INVALID_STREAMSNAPSHOT_NAME": 2103,
	"STREAMSNAPSHOT_EXISTS":       2104,
	"STREAMSNAPSHOT_NOT_FOUND":    2105,
	"WRONG_GROUP_LOCATION":        3000,
	"INVALID_GROUP_ID":            3001,
	"GROUP_EXISTS":                3002,
	"GROUP_NOT_FOUND":             3003,
	"STALE_GROUP_INFO":            3004,
	"INVALID_KEY":                 6000,
	"KEY_EXISTS":                  6001,
	"KEY_NOT_FOUND":               6002,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

type RelationType int32

const (
	RelationType_CHILDREN         RelationType = 0
	RelationType_PARENTS          RelationType = 1
	RelationType_CHILDREN_PARENTS RelationType = 2
)

var RelationType_name = map[int32]string{
	0: "CHILDREN",
	1: "PARENTS",
	2: "CHILDREN_PARENTS",
}

var RelationType_value = map[string]int32{
	"CHILDREN":         0,
	"PARENTS":          1,
	"CHILDREN_PARENTS": 2,
}

func (x RelationType) String() string {
	return proto.EnumName(RelationType_name, int32(x))
}

func (RelationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

type GetActiveRangesRequest struct {
	StreamId int64 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// create stream if not exists
	StreamProps          *stream.StreamProperties `protobuf:"bytes,2,opt,name=stream_props,json=streamProps,proto3" json:"stream_props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetActiveRangesRequest) Reset()         { *m = GetActiveRangesRequest{} }
func (m *GetActiveRangesRequest) String() string { return proto.CompactTextString(m) }
func (*GetActiveRangesRequest) ProtoMessage()    {}
func (*GetActiveRangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *GetActiveRangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActiveRangesRequest.Unmarshal(m, b)
}
func (m *GetActiveRangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActiveRangesRequest.Marshal(b, m, deterministic)
}
func (m *GetActiveRangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActiveRangesRequest.Merge(m, src)
}
func (m *GetActiveRangesRequest) XXX_Size() int {
	return xxx_messageInfo_GetActiveRangesRequest.Size(m)
}
func (m *GetActiveRangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActiveRangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActiveRangesRequest proto.InternalMessageInfo

func (m *GetActiveRangesRequest) GetStreamId() int64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *GetActiveRangesRequest) GetStreamProps() *stream.StreamProperties {
	if m != nil {
		return m.StreamProps
	}
	return nil
}

type GetActiveRangesResponse struct {
	Code                 StatusCode       `protobuf:"varint,1,opt,name=code,proto3,enum=bookkeeper.proto.storage.StatusCode" json:"code,omitempty"`
	Ranges               []*RelatedRanges `protobuf:"bytes,2,rep,name=ranges,proto3" json:"ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetActiveRangesResponse) Reset()         { *m = GetActiveRangesResponse{} }
func (m *GetActiveRangesResponse) String() string { return proto.CompactTextString(m) }
func (*GetActiveRangesResponse) ProtoMessage()    {}
func (*GetActiveRangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *GetActiveRangesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActiveRangesResponse.Unmarshal(m, b)
}
func (m *GetActiveRangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActiveRangesResponse.Marshal(b, m, deterministic)
}
func (m *GetActiveRangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActiveRangesResponse.Merge(m, src)
}
func (m *GetActiveRangesResponse) XXX_Size() int {
	return xxx_messageInfo_GetActiveRangesResponse.Size(m)
}
func (m *GetActiveRangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActiveRangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActiveRangesResponse proto.InternalMessageInfo

func (m *GetActiveRangesResponse) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_SUCCESS
}

func (m *GetActiveRangesResponse) GetRanges() []*RelatedRanges {
	if m != nil {
		return m.Ranges
	}
	return nil
}

type RelatedRanges struct {
	Props                *stream.RangeProperties `protobuf:"bytes,1,opt,name=props,proto3" json:"props,omitempty"`
	Type                 RelationType            `protobuf:"varint,2,opt,name=type,proto3,enum=bookkeeper.proto.storage.RelationType" json:"type,omitempty"`
	RelatedRanges        []int64                 `protobuf:"varint,3,rep,packed,name=related_ranges,json=relatedRanges,proto3" json:"related_ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RelatedRanges) Reset()         { *m = RelatedRanges{} }
func (m *RelatedRanges) String() string { return proto.CompactTextString(m) }
func (*RelatedRanges) ProtoMessage()    {}
func (*RelatedRanges) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *RelatedRanges) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelatedRanges.Unmarshal(m, b)
}
func (m *RelatedRanges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelatedRanges.Marshal(b, m, deterministic)
}
func (m *RelatedRanges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelatedRanges.Merge(m, src)
}
func (m *RelatedRanges) XXX_Size() int {
	return xxx_messageInfo_RelatedRanges.Size(m)
}
func (m *RelatedRanges) XXX_DiscardUnknown() {
	xxx_messageInfo_RelatedRanges.DiscardUnknown(m)
}

var xxx_messageInfo_RelatedRanges proto.InternalMessageInfo

func (m *RelatedRanges) GetProps() *stream.RangeProperties {
	if m != nil {
		return m.Props
	}
	return nil
}

func (m *RelatedRanges) GetType() RelationType {
	if m != nil {
		return m.Type
	}
	return RelationType_CHILDREN
}

func (m *RelatedRanges) GetRelatedRanges() []int64 {
	if m != nil {
		return m.RelatedRanges
	}
	return nil
}

type CreateNamespaceRequest struct {
	Name                 string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NsConf               *stream.NamespaceConfiguration `protobuf:"bytes,2,opt,name=ns_conf,json=nsConf,proto3" json:"ns_conf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *CreateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRequest.Merge(m, src)
}
func (m *CreateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRequest.Size(m)
}
func (m *CreateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRequest proto.InternalMessageInfo

func (m *CreateNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateNamespaceRequest) GetNsConf() *stream.NamespaceConfiguration {
	if m != nil {
		return m.NsConf
	}
	return nil
}

type CreateNamespaceResponse struct {
	Code                 StatusCode                  `protobuf:"varint,1,opt,name=code,proto3,enum=bookkeeper.proto.storage.StatusCode" json:"code,omitempty"`
	NsProps              *stream.NamespaceProperties `protobuf:"bytes,2,opt,name=ns_props,json=nsProps,proto3" json:"ns_props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CreateNamespaceResponse) Reset()         { *m = CreateNamespaceResponse{} }
func (m *CreateNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceResponse) ProtoMessage()    {}
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}

func (m *CreateNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceResponse.Unmarshal(m, b)
}
func (m *CreateNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceResponse.Merge(m, src)
}
func (m *CreateNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceResponse.Size(m)
}
func (m *CreateNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceResponse proto.InternalMessageInfo

func (m *CreateNamespaceResponse) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_SUCCESS
}

func (m *CreateNamespaceResponse) GetNsProps() *stream.NamespaceProperties {
	if m != nil {
		return m.NsProps
	}
	return nil
}

type DeleteNamespaceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNamespaceRequest) Reset()         { *m = DeleteNamespaceRequest{} }
func (m *DeleteNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceRequest) ProtoMessage()    {}
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5}
}

func (m *DeleteNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceRequest.Unmarshal(m, b)
}
func (m *DeleteNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceRequest.Merge(m, src)
}
func (m *DeleteNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceRequest.Size(m)
}
func (m *DeleteNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceRequest proto.InternalMessageInfo

func (m *DeleteNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteNamespaceResponse struct {
	Code                 StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=bookkeeper.proto.storage.StatusCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeleteNamespaceResponse) Reset()         { *m = DeleteNamespaceResponse{} }
func (m *DeleteNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceResponse) ProtoMessage()    {}
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6}
}

func (m *DeleteNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceResponse.Unmarshal(m, b)
}
func (m *DeleteNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceResponse.Merge(m, src)
}
func (m *DeleteNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceResponse.Size(m)
}
func (m *DeleteNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceResponse proto.InternalMessageInfo

func (m *DeleteNamespaceResponse) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_SUCCESS
}

type GetNamespaceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNamespaceRequest) Reset()         { *m = GetNamespaceRequest{} }
func (m *GetNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*GetNamespaceRequest) ProtoMessage()    {}
func (*GetNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{7}
}

func (m *GetNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNamespaceRequest.Unmarshal(m, b)
}
func (m *GetNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *GetNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNamespaceRequest.Merge(m, src)
}
func (m *GetNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_GetNamespaceRequest.Size(m)
}
func (m *GetNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNamespaceRequest proto.InternalMessageInfo

func (m *GetNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetNamespaceResponse struct {
	Code                 StatusCode                  `protobuf:"varint,1,opt,name=code,proto3,enum=bookkeeper.proto.storage.StatusCode" json:"code,omitempty"`
	NsProps              *stream.NamespaceProperties `protobuf:"bytes,2,opt,name=ns_props,json=nsProps,proto3" json:"ns_props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetNamespaceResponse) Reset()         { *m = GetNamespaceResponse{} }
func (m *GetNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*GetNamespaceResponse) ProtoMessage()    {}
func (*GetNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{8}
}

func (m *GetNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNamespaceResponse.Unmarshal(m, b)
}
func (m *GetNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *GetNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNamespaceResponse.Merge(m, src)
}
func (m *GetNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_GetNamespaceResponse.Size(m)
}
func (m *GetNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNamespaceResponse proto.InternalMessageInfo

func (m *GetNamespaceResponse) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_SUCCESS
}

func (m *GetNamespaceResponse) GetNsProps() *stream.NamespaceProperties {
	if m != nil {
		return m.NsProps
	}
	return nil
}

type CreateStreamRequest struct {
	NsName               string                      `protobuf:"bytes,1,opt,name=ns_name,json=nsName,proto3" json:"ns_name,omitempty"`
	Name                 string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StreamConf           *stream.StreamConfiguration `protobuf:"bytes,3,opt,name=stream_conf,json=streamConf,proto3" json:"stream_conf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CreateStreamRequest) Reset()         { *m = CreateStreamRequest{} }
func (m *CreateStreamRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStreamRequest) ProtoMessage()    {}
func (*CreateStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{9}
}

func (m *CreateStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStreamRequest.Unmarshal(m, b)
}
func (m *CreateStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStreamRequest.Marshal(b, m, deterministic)
}
func (m *CreateStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStreamRequest.Merge(m, src)
}
func (m *CreateStreamRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStreamRequest.Size(m)
}
func (m *CreateStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStreamRequest proto.InternalMessageInfo

func (m *CreateStreamRequest) GetNsName() string {
	if m != nil {
		return m.NsName
	}
	return ""
}

func (m *CreateStreamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateStreamRequest) GetStreamConf() *stream.StreamConfiguration {
	if m != nil {
		return m.StreamConf
	}
	return nil
}

type CreateStreamResponse struct {
	Code                 StatusCode               `protobuf:"varint,1,opt,name=code,proto3,enum=bookkeeper.proto.storage.StatusCode" json:"code,omitempty"`
	StreamProps          *stream.StreamProperties `protobuf:"bytes,2,opt,name=stream_props,json=streamProps,proto3" json:"stream_props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CreateStreamResponse) Reset()         { *m = CreateStreamResponse{} }
func (m *CreateStreamResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStreamResponse) ProtoMessage()    {}
func (*CreateStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{10}
}

func (m *CreateStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStreamResponse.Unmarshal(m, b)
}
func (m *CreateStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStreamResponse.Marshal(b, m, deterministic)
}
func (m *CreateStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStreamResponse.Merge(m, src)
}
func (m *CreateStreamResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStreamResponse.Size(m)
}
func (m *CreateStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStreamResponse proto.InternalMessageInfo

func (m *CreateStreamResponse) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_SUCCESS
}

func (m *CreateStreamResponse) GetStreamProps() *stream.StreamProperties {
	if m != nil {
		return m.StreamProps
	}
	return nil
}

type DeleteStreamRequest struct {
	NsName               string   `protobuf:"bytes,1,opt,name=ns_name,json=nsName,proto3" json:"ns_name,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStreamRequest) Reset()         { *m = DeleteStreamRequest{} }
func (m *DeleteStreamRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStreamRequest) ProtoMessage()    {}
func (*DeleteStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{11}
}

func (m *DeleteStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStreamRequest.Unmarshal(m, b)
}
func (m *DeleteStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStreamRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStreamRequest.Merge(m, src)
}
func (m *DeleteStreamRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStreamRequest.Size(m)
}
func (m *DeleteStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStreamRequest proto.InternalMessageInfo

func (m *DeleteStreamRequest) GetNsName() string {
	if m != nil {
		return m.NsName
	}
	return ""
}

func (m *DeleteStreamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteStreamResponse struct {
	Code                 StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=bookkeeper.proto.storage.StatusCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeleteStreamResponse) Reset()         { *m = DeleteStreamResponse{} }
func (m *DeleteStreamResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStreamResponse) ProtoMessage()    {}
func (*DeleteStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{12}
}

func (m *DeleteStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStreamResponse.Unmarshal(m, b)
}
func (m *DeleteStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStreamResponse.Marshal(b, m, deterministic)
}
func (m *DeleteStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStreamResponse.Merge(m, src)
}
func (m *DeleteStreamResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteStreamResponse.Size(m)
}
func (m *DeleteStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStreamResponse proto.InternalMessageInfo

func (m *DeleteStreamResponse) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_SUCCESS
}

type GetStreamRequest struct {
	// Types that are valid to be assigned to Id:
	//	*GetStreamRequest_StreamName
	//	*GetStreamRequest_StreamId
	Id                   isGetStreamRequest_Id `protobuf_oneof:"id"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetStreamRequest) Reset()         { *m = GetStreamRequest{} }
func (m *GetStreamRequest) String() string { return proto.CompactTextString(m) }
func (*GetStreamRequest) ProtoMessage()    {}
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{13}
}

func (m *GetStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamRequest.Unmarshal(m, b)
}
func (m *GetStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamRequest.Marshal(b, m, deterministic)
}
func (m *GetStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamRequest.Merge(m, src)
}
func (m *GetStreamRequest) XXX_Size() int {
	return xxx_messageInfo_GetStreamRequest.Size(m)
}
func (m *GetStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamRequest proto.InternalMessageInfo

type isGetStreamRequest_Id interface {
	isGetStreamRequest_Id()
}

type GetStreamRequest_StreamName struct {
	StreamName *stream.StreamName `protobuf:"bytes,1,opt,name=stream_name,json=streamName,proto3,oneof"`
}

type GetStreamRequest_StreamId struct {
	StreamId int64 `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3,oneof"`
}

func (*GetStreamRequest_StreamName) isGetStreamRequest_Id() {}

func (*GetStreamRequest_StreamId) isGetStreamRequest_Id() {}

func (m *GetStreamRequest) GetId() isGetStreamRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetStreamRequest) GetStreamName() *stream.StreamName {
	if x, ok := m.GetId().(*GetStreamRequest_StreamName); ok {
		return x.StreamName
	}
	return nil
}

func (m *GetStreamRequest) GetStreamId() int64 {
	if x, ok := m.GetId().(*GetStreamRequest_StreamId); ok {
		return x.StreamId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetStreamRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetStreamRequest_StreamName)(nil),
		(*GetStreamRequest_StreamId)(nil),
	}
}

type GetStreamResponse struct {
	Code                 StatusCode               `protobuf:"varint,1,opt,name=code,proto3,enum=bookkeeper.proto.storage.StatusCode" json:"code,omitempty"`
	StreamProps          *stream.StreamProperties `protobuf:"bytes,2,opt,name=stream_props,json=streamProps,proto3" json:"stream_props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetStreamResponse) Reset()         { *m = GetStreamResponse{} }
func (m *GetStreamResponse) String() string { return proto.CompactTextString(m) }
func (*GetStreamResponse) ProtoMessage()    {}
func (*GetStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{14}
}

func (m *GetStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamResponse.Unmarshal(m, b)
}
func (m *GetStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamResponse.Marshal(b, m, deterministic)
}
func (m *GetStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamResponse.Merge(m, src)
}
func (m *GetStreamResponse) XXX_Size() int {
	return xxx_messageInfo_GetStreamResponse.Size(m)
}
func (m *GetStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamResponse proto.InternalMessageInfo

func (m *GetStreamResponse) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_SUCCESS
}

func (m *GetStreamResponse) GetStreamProps() *stream.StreamProperties {
	if m != nil {
		return m.StreamProps
	}
	return nil
}

type StorageContainerEndpoint struct {
	StorageContainerId   int64              `protobuf:"varint,1,opt,name=storage_container_id,json=storageContainerId,proto3" json:"storage_container_id,omitempty"`
	Revision             int64              `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	RwEndpoint           *common.Endpoint   `protobuf:"bytes,3,opt,name=rw_endpoint,json=rwEndpoint,proto3" json:"rw_endpoint,omitempty"`
	RoEndpoint           []*common.Endpoint `protobuf:"bytes,4,rep,name=ro_endpoint,json=roEndpoint,proto3" json:"ro_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StorageContainerEndpoint) Reset()         { *m = StorageContainerEndpoint{} }
func (m *StorageContainerEndpoint) String() string { return proto.CompactTextString(m) }
func (*StorageContainerEndpoint) ProtoMessage()    {}
func (*StorageContainerEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{15}
}

func (m *StorageContainerEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageContainerEndpoint.Unmarshal(m, b)
}
func (m *StorageContainerEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageContainerEndpoint.Marshal(b, m, deterministic)
}
func (m *StorageContainerEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageContainerEndpoint.Merge(m, src)
}
func (m *StorageContainerEndpoint) XXX_Size() int {
	return xxx_messageInfo_StorageContainerEndpoint.Size(m)
}
func (m *StorageContainerEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageContainerEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_StorageContainerEndpoint proto.InternalMessageInfo

func (m *StorageContainerEndpoint) GetStorageContainerId() int64 {
	if m != nil {
		return m.StorageContainerId
	}
	return 0
}

func (m *StorageContainerEndpoint) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *StorageContainerEndpoint) GetRwEndpoint() *common.Endpoint {
	if m != nil {
		return m.RwEndpoint
	}
	return nil
}

func (m *StorageContainerEndpoint) GetRoEndpoint() []*common.Endpoint {
	if m != nil {
		return m.RoEndpoint
	}
	return nil
}

type OneStorageContainerEndpointRequest struct {
	StorageContainer     int64    `protobuf:"varint,1,opt,name=storage_container,json=storageContainer,proto3" json:"storage_container,omitempty"`
	Revision             int64    `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneStorageContainerEndpointRequest) Reset()         { *m = OneStorageContainerEndpointRequest{} }
func (m *OneStorageContainerEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*OneStorageContainerEndpointRequest) ProtoMessage()    {}
func (*OneStorageContainerEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{16}
}

func (m *OneStorageContainerEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneStorageContainerEndpointRequest.Unmarshal(m, b)
}
func (m *OneStorageContainerEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneStorageContainerEndpointRequest.Marshal(b, m, deterministic)
}
func (m *OneStorageContainerEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneStorageContainerEndpointRequest.Merge(m, src)
}
func (m *OneStorageContainerEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_OneStorageContainerEndpointRequest.Size(m)
}
func (m *OneStorageContainerEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OneStorageContainerEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OneStorageContainerEndpointRequest proto.InternalMessageInfo

func (m *OneStorageContainerEndpointRequest) GetStorageContainer() int64 {
	if m != nil {
		return m.StorageContainer
	}
	return 0
}

func (m *OneStorageContainerEndpointRequest) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

type GetStorageContainerEndpointRequest struct {
	Requests             []*OneStorageContainerEndpointRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *GetStorageContainerEndpointRequest) Reset()         { *m = GetStorageContainerEndpointRequest{} }
func (m *GetStorageContainerEndpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetStorageContainerEndpointRequest) ProtoMessage()    {}
func (*GetStorageContainerEndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{17}
}

func (m *GetStorageContainerEndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorageContainerEndpointRequest.Unmarshal(m, b)
}
func (m *GetStorageContainerEndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorageContainerEndpointRequest.Marshal(b, m, deterministic)
}
func (m *GetStorageContainerEndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorageContainerEndpointRequest.Merge(m, src)
}
func (m *GetStorageContainerEndpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetStorageContainerEndpointRequest.Size(m)
}
func (m *GetStorageContainerEndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorageContainerEndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorageContainerEndpointRequest proto.InternalMessageInfo

func (m *GetStorageContainerEndpointRequest) GetRequests() []*OneStorageContainerEndpointRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type OneStorageContainerEndpointResponse struct {
	StatusCode           StatusCode                `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=bookkeeper.proto.storage.StatusCode" json:"status_code,omitempty"`
	Endpoint             *StorageContainerEndpoint `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *OneStorageContainerEndpointResponse) Reset()         { *m = OneStorageContainerEndpointResponse{} }
func (m *OneStorageContainerEndpointResponse) String() string { return proto.CompactTextString(m) }
func (*OneStorageContainerEndpointResponse) ProtoMessage()    {}
func (*OneStorageContainerEndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{18}
}

func (m *OneStorageContainerEndpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneStorageContainerEndpointResponse.Unmarshal(m, b)
}
func (m *OneStorageContainerEndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneStorageContainerEndpointResponse.Marshal(b, m, deterministic)
}
func (m *OneStorageContainerEndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneStorageContainerEndpointResponse.Merge(m, src)
}
func (m *OneStorageContainerEndpointResponse) XXX_Size() int {
	return xxx_messageInfo_OneStorageContainerEndpointResponse.Size(m)
}
func (m *OneStorageContainerEndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OneStorageContainerEndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OneStorageContainerEndpointResponse proto.InternalMessageInfo

func (m *OneStorageContainerEndpointResponse) GetStatusCode() StatusCode {
	if m != nil {
		return m.StatusCode
	}
	return StatusCode_SUCCESS
}

func (m *OneStorageContainerEndpointResponse) GetEndpoint() *StorageContainerEndpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type GetStorageContainerEndpointResponse struct {
	StatusCode           StatusCode                             `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=bookkeeper.proto.storage.StatusCode" json:"status_code,omitempty"`
	Responses            []*OneStorageContainerEndpointResponse `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *GetStorageContainerEndpointResponse) Reset()         { *m = GetStorageContainerEndpointResponse{} }
func (m *GetStorageContainerEndpointResponse) String() string { return proto.CompactTextString(m) }
func (*GetStorageContainerEndpointResponse) ProtoMessage()    {}
func (*GetStorageContainerEndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{19}
}

func (m *GetStorageContainerEndpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorageContainerEndpointResponse.Unmarshal(m, b)
}
func (m *GetStorageContainerEndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorageContainerEndpointResponse.Marshal(b, m, deterministic)
}
func (m *GetStorageContainerEndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorageContainerEndpointResponse.Merge(m, src)
}
func (m *GetStorageContainerEndpointResponse) XXX_Size() int {
	return xxx_messageInfo_GetStorageContainerEndpointResponse.Size(m)
}
func (m *GetStorageContainerEndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorageContainerEndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorageContainerEndpointResponse proto.InternalMessageInfo

func (m *GetStorageContainerEndpointResponse) GetStatusCode() StatusCode {
	if m != nil {
		return m.StatusCode
	}
	return StatusCode_SUCCESS
}

func (m *GetStorageContainerEndpointResponse) GetResponses() []*OneStorageContainerEndpointResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

func init() {
	proto.RegisterEnum("bookkeeper.proto.storage.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("bookkeeper.proto.storage.RelationType", RelationType_name, RelationType_value)
	proto.RegisterType((*GetActiveRangesRequest)(nil), "bookkeeper.proto.storage.GetActiveRangesRequest")
	proto.RegisterType((*GetActiveRangesResponse)(nil), "bookkeeper.proto.storage.GetActiveRangesResponse")
	proto.RegisterType((*RelatedRanges)(nil), "bookkeeper.proto.storage.RelatedRanges")
	proto.RegisterType((*CreateNamespaceRequest)(nil), "bookkeeper.proto.storage.CreateNamespaceRequest")
	proto.RegisterType((*CreateNamespaceResponse)(nil), "bookkeeper.proto.storage.CreateNamespaceResponse")
	proto.RegisterType((*DeleteNamespaceRequest)(nil), "bookkeeper.proto.storage.DeleteNamespaceRequest")
	proto.RegisterType((*DeleteNamespaceResponse)(nil), "bookkeeper.proto.storage.DeleteNamespaceResponse")
	proto.RegisterType((*GetNamespaceRequest)(nil), "bookkeeper.proto.storage.GetNamespaceRequest")
	proto.RegisterType((*GetNamespaceResponse)(nil), "bookkeeper.proto.storage.GetNamespaceResponse")
	proto.RegisterType((*CreateStreamRequest)(nil), "bookkeeper.proto.storage.CreateStreamRequest")
	proto.RegisterType((*CreateStreamResponse)(nil), "bookkeeper.proto.storage.CreateStreamResponse")
	proto.RegisterType((*DeleteStreamRequest)(nil), "bookkeeper.proto.storage.DeleteStreamRequest")
	proto.RegisterType((*DeleteStreamResponse)(nil), "bookkeeper.proto.storage.DeleteStreamResponse")
	proto.RegisterType((*GetStreamRequest)(nil), "bookkeeper.proto.storage.GetStreamRequest")
	proto.RegisterType((*GetStreamResponse)(nil), "bookkeeper.proto.storage.GetStreamResponse")
	proto.RegisterType((*StorageContainerEndpoint)(nil), "bookkeeper.proto.storage.StorageContainerEndpoint")
	proto.RegisterType((*OneStorageContainerEndpointRequest)(nil), "bookkeeper.proto.storage.OneStorageContainerEndpointRequest")
	proto.RegisterType((*GetStorageContainerEndpointRequest)(nil), "bookkeeper.proto.storage.GetStorageContainerEndpointRequest")
	proto.RegisterType((*OneStorageContainerEndpointResponse)(nil), "bookkeeper.proto.storage.OneStorageContainerEndpointResponse")
	proto.RegisterType((*GetStorageContainerEndpointResponse)(nil), "bookkeeper.proto.storage.GetStorageContainerEndpointResponse")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 1358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4d, 0x73, 0xdb, 0x44,
	0x18, 0xae, 0x62, 0x37, 0x1f, 0xaf, 0x9d, 0x66, 0xbb, 0x71, 0x63, 0x93, 0x4c, 0x67, 0x82, 0xca,
	0x47, 0x9a, 0xb6, 0x4e, 0x31, 0x17, 0x06, 0x5a, 0x3a, 0x8a, 0xbd, 0x71, 0x34, 0x75, 0x64, 0xb3,
	0x72, 0x42, 0x0b, 0x07, 0x8d, 0x6a, 0x6f, 0x53, 0x4f, 0x6b, 0x49, 0x48, 0x4a, 0x3a, 0xbd, 0xc0,
	0x01, 0xb8, 0x70, 0x82, 0x81, 0x0b, 0x1f, 0xc3, 0x8f, 0x60, 0x68, 0x69, 0xa1, 0x7f, 0x00, 0x4e,
	0xc0, 0x89, 0x9f, 0x51, 0x18, 0xb8, 0x33, 0xd2, 0x4a, 0xb2, 0xec, 0xd8, 0x4a, 0x9a, 0xf4, 0xd0,
	0x53, 0xb4, 0xef, 0xee, 0xfb, 0x3c, 0xcf, 0xfb, 0x21, 0xef, 0xab, 0xc0, 0xb4, 0xe3, 0x9a, 0xb6,
	0xbe, 0xcd, 0x8a, 0x96, 0x6d, 0xba, 0x26, 0x2e, 0xdc, 0x30, 0xcd, 0xdb, 0xb7, 0x19, 0xb3, 0x98,
	0xcd, 0x2d, 0xc5, 0x60, 0x7f, 0x3e, 0xdb, 0x32, 0xbb, 0x5d, 0xd3, 0xe0, 0xd6, 0xf9, 0xac, 0xe3,
	0xda, 0x4c, 0xef, 0xf2, 0x95, 0xf8, 0xb1, 0x00, 0x73, 0x55, 0xe6, 0x4a, 0x2d, 0xb7, 0xb3, 0xcb,
	0xa8, 0x6e, 0x6c, 0x33, 0x87, 0xb2, 0x0f, 0x76, 0x98, 0xe3, 0xe2, 0x05, 0x98, 0xe2, 0x47, 0xb5,
	0x4e, 0xbb, 0x20, 0x2c, 0x0a, 0x4b, 0x29, 0x3a, 0xc9, 0x0d, 0x72, 0x1b, 0xd7, 0x20, 0xc0, 0xd1,
	0x2c, 0xdb, 0xb4, 0x9c, 0xc2, 0xd8, 0xa2, 0xb0, 0x94, 0x29, 0x9d, 0x2d, 0x0e, 0x11, 0xe1, 0xb3,
	0xa9, 0xfe, 0x9f, 0x86, 0x6d, 0x5a, 0xcc, 0x76, 0x3b, 0xcc, 0xa1, 0x19, 0x27, 0xb2, 0x38, 0xe2,
	0x57, 0x02, 0xe4, 0xf7, 0xa8, 0x70, 0x2c, 0xd3, 0x70, 0x18, 0x7e, 0x03, 0xd2, 0x2d, 0xb3, 0xcd,
	0x7c, 0x05, 0x27, 0x4a, 0x2f, 0x15, 0x47, 0x85, 0x59, 0x54, 0x5d, 0xdd, 0xdd, 0x71, 0xca, 0x66,
	0x9b, 0x51, 0xdf, 0x03, 0x5f, 0x81, 0x71, 0xdb, 0xc7, 0x2a, 0x8c, 0x2d, 0xa6, 0x96, 0x32, 0xa5,
	0x57, 0x47, 0xfb, 0x52, 0x76, 0x47, 0x77, 0x59, 0x3b, 0xa0, 0x0e, 0xdc, 0xc4, 0x1f, 0x04, 0x98,
	0xee, 0xdb, 0xc1, 0x6f, 0xc3, 0x71, 0x1e, 0xaf, 0xe0, 0xc7, 0xbb, 0x34, 0x32, 0x5e, 0xff, 0x7c,
	0x2c, 0x5c, 0xee, 0x86, 0xdf, 0x84, 0xb4, 0x7b, 0xcf, 0x62, 0x7e, 0xba, 0x4e, 0x94, 0x5e, 0xd9,
	0x47, 0x50, 0xc7, 0x34, 0x9a, 0xf7, 0x2c, 0x46, 0x7d, 0x1f, 0xfc, 0x32, 0x9c, 0xb0, 0xb9, 0x18,
	0x2d, 0x08, 0x2b, 0xb5, 0x98, 0x5a, 0x4a, 0xd1, 0x69, 0x3b, 0x2e, 0x51, 0xdc, 0x85, 0xb9, 0xb2,
	0xcd, 0x74, 0x97, 0x29, 0x7a, 0x97, 0x39, 0x96, 0xde, 0x62, 0x61, 0x41, 0x31, 0xa4, 0x0d, 0xbd,
	0xcb, 0x33, 0x39, 0x45, 0xfd, 0x67, 0xbc, 0x0e, 0x13, 0x86, 0xa3, 0xb5, 0x4c, 0xe3, 0x66, 0x50,
	0xc2, 0x95, 0x91, 0x21, 0x45, 0x78, 0x65, 0xd3, 0xb8, 0xd9, 0xd9, 0xde, 0xb1, 0x7d, 0x81, 0x74,
	0xdc, 0x70, 0x3c, 0x83, 0xf8, 0x9d, 0x00, 0xf9, 0x3d, 0xc4, 0x47, 0xae, 0x61, 0x15, 0x26, 0x0d,
	0xa7, 0xaf, 0xc7, 0xce, 0xef, 0x2f, 0x30, 0x96, 0xf7, 0x09, 0xc3, 0xe1, 0x2d, 0x76, 0x1e, 0xe6,
	0x2a, 0xec, 0x0e, 0x3b, 0x58, 0x5a, 0x44, 0x15, 0xf2, 0x7b, 0x4e, 0x1f, 0x35, 0x16, 0xf1, 0x2c,
	0xcc, 0x56, 0x99, 0x7b, 0x20, 0xfe, 0xaf, 0x05, 0xc8, 0xf5, 0x9f, 0x7d, 0x7e, 0x32, 0xf9, 0x85,
	0x00, 0xb3, 0xbc, 0xd0, 0xfc, 0xa5, 0x0e, 0xe3, 0xc8, 0xfb, 0xad, 0x14, 0x0b, 0x65, 0xdc, 0x70,
	0x3c, 0xa0, 0x28, 0xc0, 0xb1, 0x58, 0xdf, 0x6d, 0x40, 0xf0, 0x03, 0xc0, 0x7b, 0x2f, 0xb5, 0x8f,
	0x20, 0xce, 0xd4, 0xdf, 0x78, 0xe0, 0x44, 0x46, 0xf1, 0x7b, 0x01, 0x72, 0xfd, 0x9a, 0x8e, 0x9c,
	0xaf, 0x67, 0xfb, 0x0b, 0xb7, 0x0a, 0xb3, 0xbc, 0xa1, 0x0e, 0x9f, 0x33, 0xb1, 0x01, 0xb9, 0x7e,
	0x8c, 0x23, 0x77, 0xe4, 0x47, 0x80, 0xaa, 0xcc, 0xed, 0x97, 0xb4, 0x16, 0x55, 0x26, 0x92, 0x95,
	0x29, 0x9d, 0xd9, 0x27, 0x6c, 0x4f, 0xf3, 0xfa, 0xb1, 0xb0, 0x24, 0x7e, 0x04, 0xa7, 0xe3, 0xd7,
	0x87, 0x17, 0x46, 0x6a, 0xfd, 0x58, 0xef, 0x02, 0x59, 0x4d, 0xc3, 0x58, 0xa7, 0x2d, 0x7e, 0x2b,
	0xc0, 0xc9, 0x98, 0x82, 0xe7, 0xac, 0x68, 0x4f, 0x04, 0x28, 0xa8, 0x9c, 0xaa, 0x6c, 0x1a, 0xae,
	0xde, 0x31, 0x98, 0x4d, 0x8c, 0xb6, 0x65, 0x76, 0x0c, 0x17, 0x5f, 0x84, 0x5c, 0x20, 0xc3, 0x6b,
	0x61, 0xbe, 0xd9, 0xbb, 0x29, 0xb1, 0x33, 0xe0, 0x27, 0xb7, 0xf1, 0x3c, 0x4c, 0xda, 0x6c, 0xb7,
	0xe3, 0x74, 0x4c, 0x83, 0x27, 0x84, 0x46, 0x6b, 0xbc, 0x0a, 0x19, 0xfb, 0xae, 0xc6, 0x02, 0xf0,
	0xe0, 0x7d, 0x78, 0x71, 0xaf, 0xee, 0xe0, 0x2a, 0x0f, 0x55, 0x50, 0xb0, 0xef, 0x46, 0x8a, 0x3c,
	0x0c, 0xb3, 0x87, 0x91, 0xf6, 0x2f, 0xbd, 0x03, 0x61, 0x98, 0xe1, 0xb3, 0xd8, 0x05, 0xb1, 0x6e,
	0xb0, 0x51, 0x41, 0x87, 0x3d, 0x72, 0x0e, 0x4e, 0xee, 0x89, 0x3d, 0x08, 0x1c, 0x0d, 0x06, 0x9e,
	0x14, 0xb6, 0xf8, 0x21, 0x88, 0x7e, 0xf9, 0x93, 0xe9, 0xae, 0x79, 0x08, 0xfe, 0xa3, 0x77, 0xf1,
	0x7a, 0x51, 0x5d, 0x1a, 0xdd, 0x13, 0xfb, 0xcb, 0xa7, 0x11, 0x9a, 0xf8, 0x58, 0x80, 0x33, 0x89,
	0x0e, 0x41, 0x47, 0x12, 0xef, 0xa5, 0xf0, 0x7a, 0x4d, 0x7b, 0xea, 0xc6, 0x04, 0x27, 0x7a, 0xc6,
	0x0a, 0x4c, 0x46, 0xe5, 0xe1, 0xad, 0x59, 0x4a, 0xc2, 0x18, 0x21, 0x2a, 0xc2, 0x10, 0x7f, 0x15,
	0xe0, 0x4c, 0x62, 0xfe, 0x9e, 0xad, 0xfc, 0xf7, 0x61, 0xca, 0x0e, 0x20, 0xc3, 0x99, 0xea, 0xf2,
	0x21, 0x0b, 0xc1, 0x51, 0x68, 0x0f, 0x6f, 0xf9, 0xb7, 0x34, 0x40, 0x8f, 0x17, 0x67, 0x60, 0x42,
	0xdd, 0x2c, 0x97, 0x89, 0xaa, 0xa2, 0x63, 0xde, 0x62, 0x4d, 0x92, 0x6b, 0x9b, 0x94, 0x20, 0x01,
	0x23, 0xc8, 0xac, 0x4a, 0x15, 0x8d, 0x92, 0x77, 0x36, 0x89, 0xda, 0x44, 0x9f, 0xa7, 0xf0, 0x0c,
	0x80, 0x5c, 0xab, 0x91, 0xaa, 0x54, 0xd3, 0xea, 0x0d, 0xf4, 0x65, 0x0a, 0xcf, 0xc3, 0x29, 0x59,
	0x69, 0x12, 0xaa, 0x48, 0x35, 0x4d, 0x25, 0x74, 0x8b, 0x50, 0x8d, 0x50, 0x5a, 0xa7, 0xe8, 0xdf,
	0x14, 0xce, 0xc1, 0x8c, 0x52, 0x6f, 0x6a, 0xf2, 0x46, 0xa3, 0x46, 0x36, 0x88, 0xd2, 0x24, 0x15,
	0xf4, 0x9f, 0x0f, 0xb1, 0xa9, 0x90, 0x6b, 0x0d, 0x52, 0xf6, 0x0c, 0x7f, 0xa5, 0x43, 0x96, 0x2d,
	0x42, 0x55, 0xb9, 0xae, 0xa0, 0x4f, 0x26, 0xf0, 0x49, 0xc8, 0x72, 0xde, 0x2d, 0xd9, 0x37, 0x7d,
	0x3a, 0x81, 0x17, 0x60, 0x4e, 0x56, 0xb6, 0xa4, 0x9a, 0x5c, 0xd1, 0x14, 0x69, 0x83, 0xa8, 0x0d,
	0xa9, 0x4c, 0xfc, 0x27, 0xf4, 0xfb, 0x0c, 0x3e, 0x05, 0xa8, 0x67, 0x24, 0xd7, 0x64, 0xb5, 0xa9,
	0xa2, 0x3f, 0x66, 0x70, 0x01, 0x66, 0x63, 0x67, 0xeb, 0x4d, 0x6d, 0xad, 0xbe, 0xa9, 0x54, 0xd0,
	0x9f, 0xfe, 0x4e, 0x88, 0xa6, 0x36, 0x29, 0x91, 0x36, 0x38, 0xd4, 0x8f, 0x08, 0x63, 0x98, 0x0e,
	0x2c, 0x01, 0xce, 0x7d, 0xe4, 0xc1, 0x87, 0xa7, 0x22, 0x90, 0x07, 0x08, 0x2f, 0xc2, 0x42, 0x3f,
	0x88, 0xaa, 0x48, 0x0d, 0x75, 0xbd, 0xde, 0xe4, 0x60, 0x3f, 0x21, 0x2f, 0x39, 0x03, 0x3b, 0x01,
	0xe8, 0x43, 0x84, 0x4f, 0x43, 0x61, 0xd0, 0x2b, 0x02, 0x7f, 0x84, 0xf0, 0x0b, 0x90, 0x7b, 0x97,
	0xd6, 0x95, 0xaa, 0x56, 0xa5, 0xf5, 0xcd, 0x86, 0x56, 0xab, 0x97, 0xa5, 0xa6, 0x97, 0x8a, 0x87,
	0x79, 0x4f, 0x4e, 0xc8, 0xcb, 0x37, 0xe5, 0x0a, 0x7a, 0x94, 0xf7, 0x92, 0xc6, 0x97, 0x01, 0xc7,
	0xcf, 0x79, 0xaf, 0x00, 0xdc, 0xd4, 0x83, 0xfe, 0x25, 0xcf, 0xc3, 0x91, 0x6a, 0x24, 0xf4, 0x56,
	0xd6, 0xea, 0xe8, 0x71, 0xde, 0x2b, 0x43, 0x08, 0x7b, 0x95, 0x5c, 0x47, 0x4f, 0x8a, 0x5e, 0xa5,
	0xae, 0x92, 0xeb, 0x21, 0xde, 0xdf, 0x45, 0x2f, 0x39, 0x9e, 0xa1, 0x87, 0xf6, 0x4f, 0x71, 0xf9,
	0x0a, 0x64, 0xe3, 0x13, 0x34, 0xce, 0xc2, 0x64, 0x79, 0x5d, 0xae, 0x55, 0x28, 0x51, 0x78, 0x3b,
	0x35, 0x24, 0x4a, 0x94, 0xa6, 0x8a, 0x04, 0x9c, 0x03, 0x14, 0x6e, 0x69, 0xa1, 0x75, 0xac, 0xf4,
	0x99, 0x00, 0x68, 0x83, 0xb9, 0xba, 0x3f, 0x54, 0xab, 0xcc, 0xde, 0xed, 0xb4, 0x18, 0xde, 0x85,
	0x99, 0x81, 0xaf, 0x14, 0x7c, 0x71, 0x74, 0xff, 0x0f, 0xff, 0xac, 0x9a, 0x7f, 0xed, 0x29, 0x3c,
	0xf8, 0xbb, 0x51, 0xba, 0x7f, 0x1c, 0x10, 0x35, 0x4d, 0x77, 0x50, 0xcc, 0xc0, 0xb8, 0x9d, 0x24,
	0x66, 0xf8, 0x27, 0x41, 0x92, 0x98, 0x51, 0xb3, 0xfc, 0x2e, 0xcc, 0x0c, 0x8c, 0xc6, 0x49, 0xbc,
	0xc3, 0x67, 0xee, 0x24, 0xde, 0x51, 0x73, 0x77, 0x17, 0xb2, 0xf1, 0x89, 0x18, 0x5f, 0x48, 0xcc,
	0xe3, 0x1e, 0xc6, 0xe2, 0x41, 0x8f, 0xf7, 0xe8, 0xe2, 0x03, 0x65, 0x12, 0xdd, 0x90, 0x61, 0x38,
	0x89, 0x6e, 0xe8, 0x9c, 0xda, 0x85, 0x6c, 0x7c, 0xb6, 0x4b, 0xa2, 0x1b, 0x32, 0x47, 0x26, 0xd1,
	0x0d, 0x1d, 0x19, 0xdb, 0x30, 0x15, 0x8d, 0x5d, 0x78, 0x39, 0x31, 0x35, 0xfd, 0x44, 0xe7, 0x0e,
	0x74, 0x36, 0xe8, 0xdb, 0x07, 0x02, 0xe4, 0x07, 0xaf, 0x80, 0xb0, 0x7d, 0xbf, 0x11, 0x60, 0x21,
	0xe1, 0xea, 0xc2, 0x97, 0xf6, 0x21, 0x4a, 0xbc, 0xe1, 0xe7, 0x2f, 0x1f, 0xd2, 0x9b, 0x0b, 0x5f,
	0xbd, 0x0d, 0xcb, 0xa6, 0xbd, 0x5d, 0xd4, 0x2d, 0xbd, 0x75, 0x8b, 0xc5, 0xa1, 0xe2, 0xff, 0x3b,
	0x09, 0x11, 0x1b, 0xc2, 0x7b, 0x6f, 0x6d, 0x77, 0xdc, 0x5b, 0x3b, 0x37, 0xbc, 0xc9, 0x6a, 0xc5,
	0xba, 0xc5, 0xba, 0x5d, 0x66, 0xaf, 0x6c, 0x9b, 0x17, 0xac, 0x9d, 0x3b, 0x8e, 0x6e, 0x5f, 0xf0,
	0x6e, 0x50, 0xb6, 0xd2, 0x43, 0x59, 0xf1, 0xdd, 0x57, 0x02, 0xf7, 0x1b, 0xe3, 0xfe, 0xf2, 0xf5,
	0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x9e, 0x46, 0xda, 0xd0, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetaRangeServiceClient is the client API for MetaRangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaRangeServiceClient interface {
	GetActiveRanges(ctx context.Context, in *GetActiveRangesRequest, opts ...grpc.CallOption) (*GetActiveRangesResponse, error)
}

type metaRangeServiceClient struct {
	cc *grpc.ClientConn
}

func NewMetaRangeServiceClient(cc *grpc.ClientConn) MetaRangeServiceClient {
	return &metaRangeServiceClient{cc}
}

func (c *metaRangeServiceClient) GetActiveRanges(ctx context.Context, in *GetActiveRangesRequest, opts ...grpc.CallOption) (*GetActiveRangesResponse, error) {
	out := new(GetActiveRangesResponse)
	err := c.cc.Invoke(ctx, "/bookkeeper.proto.storage.MetaRangeService/GetActiveRanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaRangeServiceServer is the server API for MetaRangeService service.
type MetaRangeServiceServer interface {
	GetActiveRanges(context.Context, *GetActiveRangesRequest) (*GetActiveRangesResponse, error)
}

// UnimplementedMetaRangeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetaRangeServiceServer struct {
}

func (*UnimplementedMetaRangeServiceServer) GetActiveRanges(ctx context.Context, req *GetActiveRangesRequest) (*GetActiveRangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveRanges not implemented")
}

func RegisterMetaRangeServiceServer(s *grpc.Server, srv MetaRangeServiceServer) {
	s.RegisterService(&_MetaRangeService_serviceDesc, srv)
}

func _MetaRangeService_GetActiveRanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveRangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaRangeServiceServer).GetActiveRanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookkeeper.proto.storage.MetaRangeService/GetActiveRanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaRangeServiceServer).GetActiveRanges(ctx, req.(*GetActiveRangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetaRangeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bookkeeper.proto.storage.MetaRangeService",
	HandlerType: (*MetaRangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActiveRanges",
			Handler:    _MetaRangeService_GetActiveRanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// RootRangeServiceClient is the client API for RootRangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RootRangeServiceClient interface {
	//
	// Namespace Methods
	//
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error)
	GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*GetNamespaceResponse, error)
	//
	// Stream Methods
	//
	CreateStream(ctx context.Context, in *CreateStreamRequest, opts ...grpc.CallOption) (*CreateStreamResponse, error)
	DeleteStream(ctx context.Context, in *DeleteStreamRequest, opts ...grpc.CallOption) (*DeleteStreamResponse, error)
	GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*GetStreamResponse, error)
}

type rootRangeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRootRangeServiceClient(cc *grpc.ClientConn) RootRangeServiceClient {
	return &rootRangeServiceClient{cc}
}

func (c *rootRangeServiceClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, "/bookkeeper.proto.storage.RootRangeService/CreateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootRangeServiceClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error) {
	out := new(DeleteNamespaceResponse)
	err := c.cc.Invoke(ctx, "/bookkeeper.proto.storage.RootRangeService/DeleteNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootRangeServiceClient) GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*GetNamespaceResponse, error) {
	out := new(GetNamespaceResponse)
	err := c.cc.Invoke(ctx, "/bookkeeper.proto.storage.RootRangeService/GetNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootRangeServiceClient) CreateStream(ctx context.Context, in *CreateStreamRequest, opts ...grpc.CallOption) (*CreateStreamResponse, error) {
	out := new(CreateStreamResponse)
	err := c.cc.Invoke(ctx, "/bookkeeper.proto.storage.RootRangeService/CreateStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootRangeServiceClient) DeleteStream(ctx context.Context, in *DeleteStreamRequest, opts ...grpc.CallOption) (*DeleteStreamResponse, error) {
	out := new(DeleteStreamResponse)
	err := c.cc.Invoke(ctx, "/bookkeeper.proto.storage.RootRangeService/DeleteStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rootRangeServiceClient) GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*GetStreamResponse, error) {
	out := new(GetStreamResponse)
	err := c.cc.Invoke(ctx, "/bookkeeper.proto.storage.RootRangeService/GetStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RootRangeServiceServer is the server API for RootRangeService service.
type RootRangeServiceServer interface {
	//
	// Namespace Methods
	//
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error)
	GetNamespace(context.Context, *GetNamespaceRequest) (*GetNamespaceResponse, error)
	//
	// Stream Methods
	//
	CreateStream(context.Context, *CreateStreamRequest) (*CreateStreamResponse, error)
	DeleteStream(context.Context, *DeleteStreamRequest) (*DeleteStreamResponse, error)
	GetStream(context.Context, *GetStreamRequest) (*GetStreamResponse, error)
}

// UnimplementedRootRangeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRootRangeServiceServer struct {
}

func (*UnimplementedRootRangeServiceServer) CreateNamespace(ctx context.Context, req *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (*UnimplementedRootRangeServiceServer) DeleteNamespace(ctx context.Context, req *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}
func (*UnimplementedRootRangeServiceServer) GetNamespace(ctx context.Context, req *GetNamespaceRequest) (*GetNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamespace not implemented")
}
func (*UnimplementedRootRangeServiceServer) CreateStream(ctx context.Context, req *CreateStreamRequest) (*CreateStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStream not implemented")
}
func (*UnimplementedRootRangeServiceServer) DeleteStream(ctx context.Context, req *DeleteStreamRequest) (*DeleteStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStream not implemented")
}
func (*UnimplementedRootRangeServiceServer) GetStream(ctx context.Context, req *GetStreamRequest) (*GetStreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}

func RegisterRootRangeServiceServer(s *grpc.Server, srv RootRangeServiceServer) {
	s.RegisterService(&_RootRangeService_serviceDesc, srv)
}

func _RootRangeService_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootRangeServiceServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookkeeper.proto.storage.RootRangeService/CreateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootRangeServiceServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootRangeService_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootRangeServiceServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookkeeper.proto.storage.RootRangeService/DeleteNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootRangeServiceServer).DeleteNamespace(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootRangeService_GetNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootRangeServiceServer).GetNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookkeeper.proto.storage.RootRangeService/GetNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootRangeServiceServer).GetNamespace(ctx, req.(*GetNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootRangeService_CreateStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootRangeServiceServer).CreateStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookkeeper.proto.storage.RootRangeService/CreateStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootRangeServiceServer).CreateStream(ctx, req.(*CreateStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootRangeService_DeleteStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootRangeServiceServer).DeleteStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookkeeper.proto.storage.RootRangeService/DeleteStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootRangeServiceServer).DeleteStream(ctx, req.(*DeleteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RootRangeService_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootRangeServiceServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookkeeper.proto.storage.RootRangeService/GetStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootRangeServiceServer).GetStream(ctx, req.(*GetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RootRangeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bookkeeper.proto.storage.RootRangeService",
	HandlerType: (*RootRangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNamespace",
			Handler:    _RootRangeService_CreateNamespace_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _RootRangeService_DeleteNamespace_Handler,
		},
		{
			MethodName: "GetNamespace",
			Handler:    _RootRangeService_GetNamespace_Handler,
		},
		{
			MethodName: "CreateStream",
			Handler:    _RootRangeService_CreateStream_Handler,
		},
		{
			MethodName: "DeleteStream",
			Handler:    _RootRangeService_DeleteStream_Handler,
		},
		{
			MethodName: "GetStream",
			Handler:    _RootRangeService_GetStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}

// StorageContainerServiceClient is the client API for StorageContainerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageContainerServiceClient interface {
	// Get the storage container endpoints
	GetStorageContainerEndpoint(ctx context.Context, in *GetStorageContainerEndpointRequest, opts ...grpc.CallOption) (*GetStorageContainerEndpointResponse, error)
}

type storageContainerServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageContainerServiceClient(cc *grpc.ClientConn) StorageContainerServiceClient {
	return &storageContainerServiceClient{cc}
}

func (c *storageContainerServiceClient) GetStorageContainerEndpoint(ctx context.Context, in *GetStorageContainerEndpointRequest, opts ...grpc.CallOption) (*GetStorageContainerEndpointResponse, error) {
	out := new(GetStorageContainerEndpointResponse)
	err := c.cc.Invoke(ctx, "/bookkeeper.proto.storage.StorageContainerService/GetStorageContainerEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageContainerServiceServer is the server API for StorageContainerService service.
type StorageContainerServiceServer interface {
	// Get the storage container endpoints
	GetStorageContainerEndpoint(context.Context, *GetStorageContainerEndpointRequest) (*GetStorageContainerEndpointResponse, error)
}

// UnimplementedStorageContainerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStorageContainerServiceServer struct {
}

func (*UnimplementedStorageContainerServiceServer) GetStorageContainerEndpoint(ctx context.Context, req *GetStorageContainerEndpointRequest) (*GetStorageContainerEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorageContainerEndpoint not implemented")
}

func RegisterStorageContainerServiceServer(s *grpc.Server, srv StorageContainerServiceServer) {
	s.RegisterService(&_StorageContainerService_serviceDesc, srv)
}

func _StorageContainerService_GetStorageContainerEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageContainerEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageContainerServiceServer).GetStorageContainerEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookkeeper.proto.storage.StorageContainerService/GetStorageContainerEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageContainerServiceServer).GetStorageContainerEndpoint(ctx, req.(*GetStorageContainerEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageContainerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bookkeeper.proto.storage.StorageContainerService",
	HandlerType: (*StorageContainerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStorageContainerEndpoint",
			Handler:    _StorageContainerService_GetStorageContainerEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
