// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

package stream

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RangeState int32

const (
	RangeState_RANGE_ACTIVE  RangeState = 0
	RangeState_RANGE_FENCING RangeState = 1
	RangeState_RANGE_FENCED  RangeState = 2
)

var RangeState_name = map[int32]string{
	0: "RANGE_ACTIVE",
	1: "RANGE_FENCING",
	2: "RANGE_FENCED",
}

var RangeState_value = map[string]int32{
	"RANGE_ACTIVE":  0,
	"RANGE_FENCING": 1,
	"RANGE_FENCED":  2,
}

func (x RangeState) String() string {
	return proto.EnumName(RangeState_name, int32(x))
}

func (RangeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{0}
}

type RangeKeyType int32

const (
	RangeKeyType_NULL RangeKeyType = 0
	RangeKeyType_HASH RangeKeyType = 1
	RangeKeyType_RAW  RangeKeyType = 2
)

var RangeKeyType_name = map[int32]string{
	0: "NULL",
	1: "HASH",
	2: "RAW",
}

var RangeKeyType_value = map[string]int32{
	"NULL": 0,
	"HASH": 1,
	"RAW":  2,
}

func (x RangeKeyType) String() string {
	return proto.EnumName(RangeKeyType_name, int32(x))
}

func (RangeKeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{1}
}

// since stream and table are similar and exchangable,
// from the beginning, we shared the metadata management
// between streams and tables and distinguish them using
// a flag that recorded in metadata.
type StorageType int32

const (
	StorageType_STREAM StorageType = 0
	StorageType_TABLE  StorageType = 1
)

var StorageType_name = map[int32]string{
	0: "STREAM",
	1: "TABLE",
}

var StorageType_value = map[string]int32{
	"STREAM": 0,
	"TABLE":  1,
}

func (x StorageType) String() string {
	return proto.EnumName(StorageType_name, int32(x))
}

func (StorageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{2}
}

type SplitPolicyType int32

const (
	SplitPolicyType_FIXED     SplitPolicyType = 0
	SplitPolicyType_BANDWIDTH SplitPolicyType = 1
)

var SplitPolicyType_name = map[int32]string{
	0: "FIXED",
	1: "BANDWIDTH",
}

var SplitPolicyType_value = map[string]int32{
	"FIXED":     0,
	"BANDWIDTH": 1,
}

func (x SplitPolicyType) String() string {
	return proto.EnumName(SplitPolicyType_name, int32(x))
}

func (SplitPolicyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{3}
}

type StreamMetadata_LifecycleState int32

const (
	StreamMetadata_UNINIT   StreamMetadata_LifecycleState = 0
	StreamMetadata_CREATING StreamMetadata_LifecycleState = 1
	StreamMetadata_CREATED  StreamMetadata_LifecycleState = 2
	StreamMetadata_FENCING  StreamMetadata_LifecycleState = 3
	StreamMetadata_FENCED   StreamMetadata_LifecycleState = 4
)

var StreamMetadata_LifecycleState_name = map[int32]string{
	0: "UNINIT",
	1: "CREATING",
	2: "CREATED",
	3: "FENCING",
	4: "FENCED",
}

var StreamMetadata_LifecycleState_value = map[string]int32{
	"UNINIT":   0,
	"CREATING": 1,
	"CREATED":  2,
	"FENCING":  3,
	"FENCED":   4,
}

func (x StreamMetadata_LifecycleState) String() string {
	return proto.EnumName(StreamMetadata_LifecycleState_name, int32(x))
}

func (StreamMetadata_LifecycleState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{17, 0}
}

type StreamMetadata_ServingState int32

const (
	StreamMetadata_WRITABLE StreamMetadata_ServingState = 0
	StreamMetadata_READONLY StreamMetadata_ServingState = 1
)

var StreamMetadata_ServingState_name = map[int32]string{
	0: "WRITABLE",
	1: "READONLY",
}

var StreamMetadata_ServingState_value = map[string]int32{
	"WRITABLE": 0,
	"READONLY": 1,
}

func (x StreamMetadata_ServingState) String() string {
	return proto.EnumName(StreamMetadata_ServingState_name, int32(x))
}

func (StreamMetadata_ServingState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{17, 1}
}

type RangeId struct {
	ScId                 int64    `protobuf:"varint,1,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
	StreamId             int64    `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	RangeId              int64    `protobuf:"varint,3,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeId) Reset()         { *m = RangeId{} }
func (m *RangeId) String() string { return proto.CompactTextString(m) }
func (*RangeId) ProtoMessage()    {}
func (*RangeId) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{0}
}

func (m *RangeId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeId.Unmarshal(m, b)
}
func (m *RangeId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeId.Marshal(b, m, deterministic)
}
func (m *RangeId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeId.Merge(m, src)
}
func (m *RangeId) XXX_Size() int {
	return xxx_messageInfo_RangeId.Size(m)
}
func (m *RangeId) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeId.DiscardUnknown(m)
}

var xxx_messageInfo_RangeId proto.InternalMessageInfo

func (m *RangeId) GetScId() int64 {
	if m != nil {
		return m.ScId
	}
	return 0
}

func (m *RangeId) GetStreamId() int64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *RangeId) GetRangeId() int64 {
	if m != nil {
		return m.RangeId
	}
	return 0
}

type KeyRange struct {
	StartHashKey         int64    `protobuf:"varint,1,opt,name=start_hash_key,json=startHashKey,proto3" json:"start_hash_key,omitempty"`
	EndHashKey           int64    `protobuf:"varint,2,opt,name=end_hash_key,json=endHashKey,proto3" json:"end_hash_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyRange) Reset()         { *m = KeyRange{} }
func (m *KeyRange) String() string { return proto.CompactTextString(m) }
func (*KeyRange) ProtoMessage()    {}
func (*KeyRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{1}
}

func (m *KeyRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyRange.Unmarshal(m, b)
}
func (m *KeyRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyRange.Marshal(b, m, deterministic)
}
func (m *KeyRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyRange.Merge(m, src)
}
func (m *KeyRange) XXX_Size() int {
	return xxx_messageInfo_KeyRange.Size(m)
}
func (m *KeyRange) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyRange.DiscardUnknown(m)
}

var xxx_messageInfo_KeyRange proto.InternalMessageInfo

func (m *KeyRange) GetStartHashKey() int64 {
	if m != nil {
		return m.StartHashKey
	}
	return 0
}

func (m *KeyRange) GetEndHashKey() int64 {
	if m != nil {
		return m.EndHashKey
	}
	return 0
}

type RangeProperties struct {
	StartHashKey         int64    `protobuf:"varint,1,opt,name=start_hash_key,json=startHashKey,proto3" json:"start_hash_key,omitempty"`
	EndHashKey           int64    `protobuf:"varint,2,opt,name=end_hash_key,json=endHashKey,proto3" json:"end_hash_key,omitempty"`
	RangeId              int64    `protobuf:"varint,3,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	StorageContainerId   int64    `protobuf:"varint,4,opt,name=storage_container_id,json=storageContainerId,proto3" json:"storage_container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeProperties) Reset()         { *m = RangeProperties{} }
func (m *RangeProperties) String() string { return proto.CompactTextString(m) }
func (*RangeProperties) ProtoMessage()    {}
func (*RangeProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{2}
}

func (m *RangeProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeProperties.Unmarshal(m, b)
}
func (m *RangeProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeProperties.Marshal(b, m, deterministic)
}
func (m *RangeProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeProperties.Merge(m, src)
}
func (m *RangeProperties) XXX_Size() int {
	return xxx_messageInfo_RangeProperties.Size(m)
}
func (m *RangeProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeProperties.DiscardUnknown(m)
}

var xxx_messageInfo_RangeProperties proto.InternalMessageInfo

func (m *RangeProperties) GetStartHashKey() int64 {
	if m != nil {
		return m.StartHashKey
	}
	return 0
}

func (m *RangeProperties) GetEndHashKey() int64 {
	if m != nil {
		return m.EndHashKey
	}
	return 0
}

func (m *RangeProperties) GetRangeId() int64 {
	if m != nil {
		return m.RangeId
	}
	return 0
}

func (m *RangeProperties) GetStorageContainerId() int64 {
	if m != nil {
		return m.StorageContainerId
	}
	return 0
}

type RangeMetadata struct {
	Props    *RangeProperties `protobuf:"bytes,1,opt,name=props,proto3" json:"props,omitempty"`
	Revision int64            `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	State    RangeState       `protobuf:"varint,3,opt,name=state,proto3,enum=bookkeeper.proto.stream.RangeState" json:"state,omitempty"`
	// time
	CreateTime int64 `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	FenceTime  int64 `protobuf:"varint,11,opt,name=fence_time,json=fenceTime,proto3" json:"fence_time,omitempty"`
	// children and parents
	Children             []int64  `protobuf:"varint,20,rep,packed,name=children,proto3" json:"children,omitempty"`
	Parents              []int64  `protobuf:"varint,21,rep,packed,name=parents,proto3" json:"parents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeMetadata) Reset()         { *m = RangeMetadata{} }
func (m *RangeMetadata) String() string { return proto.CompactTextString(m) }
func (*RangeMetadata) ProtoMessage()    {}
func (*RangeMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{3}
}

func (m *RangeMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeMetadata.Unmarshal(m, b)
}
func (m *RangeMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeMetadata.Marshal(b, m, deterministic)
}
func (m *RangeMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeMetadata.Merge(m, src)
}
func (m *RangeMetadata) XXX_Size() int {
	return xxx_messageInfo_RangeMetadata.Size(m)
}
func (m *RangeMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RangeMetadata proto.InternalMessageInfo

func (m *RangeMetadata) GetProps() *RangeProperties {
	if m != nil {
		return m.Props
	}
	return nil
}

func (m *RangeMetadata) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *RangeMetadata) GetState() RangeState {
	if m != nil {
		return m.State
	}
	return RangeState_RANGE_ACTIVE
}

func (m *RangeMetadata) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *RangeMetadata) GetFenceTime() int64 {
	if m != nil {
		return m.FenceTime
	}
	return 0
}

func (m *RangeMetadata) GetChildren() []int64 {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *RangeMetadata) GetParents() []int64 {
	if m != nil {
		return m.Parents
	}
	return nil
}

type ParentRanges struct {
	RangeId              int64    `protobuf:"varint,1,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	ParentRangeIds       []int64  `protobuf:"varint,2,rep,packed,name=parent_range_ids,json=parentRangeIds,proto3" json:"parent_range_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParentRanges) Reset()         { *m = ParentRanges{} }
func (m *ParentRanges) String() string { return proto.CompactTextString(m) }
func (*ParentRanges) ProtoMessage()    {}
func (*ParentRanges) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{4}
}

func (m *ParentRanges) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentRanges.Unmarshal(m, b)
}
func (m *ParentRanges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentRanges.Marshal(b, m, deterministic)
}
func (m *ParentRanges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentRanges.Merge(m, src)
}
func (m *ParentRanges) XXX_Size() int {
	return xxx_messageInfo_ParentRanges.Size(m)
}
func (m *ParentRanges) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentRanges.DiscardUnknown(m)
}

var xxx_messageInfo_ParentRanges proto.InternalMessageInfo

func (m *ParentRanges) GetRangeId() int64 {
	if m != nil {
		return m.RangeId
	}
	return 0
}

func (m *ParentRanges) GetParentRangeIds() []int64 {
	if m != nil {
		return m.ParentRangeIds
	}
	return nil
}

type ParentRangesList struct {
	ChildRanges          []*ParentRanges `protobuf:"bytes,1,rep,name=child_ranges,json=childRanges,proto3" json:"child_ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ParentRangesList) Reset()         { *m = ParentRangesList{} }
func (m *ParentRangesList) String() string { return proto.CompactTextString(m) }
func (*ParentRangesList) ProtoMessage()    {}
func (*ParentRangesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{5}
}

func (m *ParentRangesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParentRangesList.Unmarshal(m, b)
}
func (m *ParentRangesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParentRangesList.Marshal(b, m, deterministic)
}
func (m *ParentRangesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParentRangesList.Merge(m, src)
}
func (m *ParentRangesList) XXX_Size() int {
	return xxx_messageInfo_ParentRangesList.Size(m)
}
func (m *ParentRangesList) XXX_DiscardUnknown() {
	xxx_messageInfo_ParentRangesList.DiscardUnknown(m)
}

var xxx_messageInfo_ParentRangesList proto.InternalMessageInfo

func (m *ParentRangesList) GetChildRanges() []*ParentRanges {
	if m != nil {
		return m.ChildRanges
	}
	return nil
}

type FixedRangeSplitPolicy struct {
	NumRanges            int32    `protobuf:"varint,1,opt,name=num_ranges,json=numRanges,proto3" json:"num_ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FixedRangeSplitPolicy) Reset()         { *m = FixedRangeSplitPolicy{} }
func (m *FixedRangeSplitPolicy) String() string { return proto.CompactTextString(m) }
func (*FixedRangeSplitPolicy) ProtoMessage()    {}
func (*FixedRangeSplitPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{6}
}

func (m *FixedRangeSplitPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedRangeSplitPolicy.Unmarshal(m, b)
}
func (m *FixedRangeSplitPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedRangeSplitPolicy.Marshal(b, m, deterministic)
}
func (m *FixedRangeSplitPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedRangeSplitPolicy.Merge(m, src)
}
func (m *FixedRangeSplitPolicy) XXX_Size() int {
	return xxx_messageInfo_FixedRangeSplitPolicy.Size(m)
}
func (m *FixedRangeSplitPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedRangeSplitPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_FixedRangeSplitPolicy proto.InternalMessageInfo

func (m *FixedRangeSplitPolicy) GetNumRanges() int32 {
	if m != nil {
		return m.NumRanges
	}
	return 0
}

type BandwidthBasedSplitPolicy struct {
	MaxRateInBytes       int32    `protobuf:"varint,1,opt,name=max_rate_in_bytes,json=maxRateInBytes,proto3" json:"max_rate_in_bytes,omitempty"`
	MinRateInBytes       int32    `protobuf:"varint,2,opt,name=min_rate_in_bytes,json=minRateInBytes,proto3" json:"min_rate_in_bytes,omitempty"`
	MaxRateInRecords     int32    `protobuf:"varint,3,opt,name=max_rate_in_records,json=maxRateInRecords,proto3" json:"max_rate_in_records,omitempty"`
	MinRateInRecords     int32    `protobuf:"varint,4,opt,name=min_rate_in_records,json=minRateInRecords,proto3" json:"min_rate_in_records,omitempty"`
	MaxSplitFactor       int32    `protobuf:"varint,5,opt,name=max_split_factor,json=maxSplitFactor,proto3" json:"max_split_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BandwidthBasedSplitPolicy) Reset()         { *m = BandwidthBasedSplitPolicy{} }
func (m *BandwidthBasedSplitPolicy) String() string { return proto.CompactTextString(m) }
func (*BandwidthBasedSplitPolicy) ProtoMessage()    {}
func (*BandwidthBasedSplitPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{7}
}

func (m *BandwidthBasedSplitPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BandwidthBasedSplitPolicy.Unmarshal(m, b)
}
func (m *BandwidthBasedSplitPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BandwidthBasedSplitPolicy.Marshal(b, m, deterministic)
}
func (m *BandwidthBasedSplitPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BandwidthBasedSplitPolicy.Merge(m, src)
}
func (m *BandwidthBasedSplitPolicy) XXX_Size() int {
	return xxx_messageInfo_BandwidthBasedSplitPolicy.Size(m)
}
func (m *BandwidthBasedSplitPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_BandwidthBasedSplitPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_BandwidthBasedSplitPolicy proto.InternalMessageInfo

func (m *BandwidthBasedSplitPolicy) GetMaxRateInBytes() int32 {
	if m != nil {
		return m.MaxRateInBytes
	}
	return 0
}

func (m *BandwidthBasedSplitPolicy) GetMinRateInBytes() int32 {
	if m != nil {
		return m.MinRateInBytes
	}
	return 0
}

func (m *BandwidthBasedSplitPolicy) GetMaxRateInRecords() int32 {
	if m != nil {
		return m.MaxRateInRecords
	}
	return 0
}

func (m *BandwidthBasedSplitPolicy) GetMinRateInRecords() int32 {
	if m != nil {
		return m.MinRateInRecords
	}
	return 0
}

func (m *BandwidthBasedSplitPolicy) GetMaxSplitFactor() int32 {
	if m != nil {
		return m.MaxSplitFactor
	}
	return 0
}

type SplitPolicy struct {
	Type SplitPolicyType `protobuf:"varint,1,opt,name=type,proto3,enum=bookkeeper.proto.stream.SplitPolicyType" json:"type,omitempty"`
	// Types that are valid to be assigned to Policy:
	//	*SplitPolicy_FixedRangePolicy
	//	*SplitPolicy_BandwidthPolicy
	Policy               isSplitPolicy_Policy `protobuf_oneof:"policy"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SplitPolicy) Reset()         { *m = SplitPolicy{} }
func (m *SplitPolicy) String() string { return proto.CompactTextString(m) }
func (*SplitPolicy) ProtoMessage()    {}
func (*SplitPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{8}
}

func (m *SplitPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitPolicy.Unmarshal(m, b)
}
func (m *SplitPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitPolicy.Marshal(b, m, deterministic)
}
func (m *SplitPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitPolicy.Merge(m, src)
}
func (m *SplitPolicy) XXX_Size() int {
	return xxx_messageInfo_SplitPolicy.Size(m)
}
func (m *SplitPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_SplitPolicy proto.InternalMessageInfo

func (m *SplitPolicy) GetType() SplitPolicyType {
	if m != nil {
		return m.Type
	}
	return SplitPolicyType_FIXED
}

type isSplitPolicy_Policy interface {
	isSplitPolicy_Policy()
}

type SplitPolicy_FixedRangePolicy struct {
	FixedRangePolicy *FixedRangeSplitPolicy `protobuf:"bytes,2,opt,name=fixed_range_policy,json=fixedRangePolicy,proto3,oneof"`
}

type SplitPolicy_BandwidthPolicy struct {
	BandwidthPolicy *BandwidthBasedSplitPolicy `protobuf:"bytes,3,opt,name=bandwidth_policy,json=bandwidthPolicy,proto3,oneof"`
}

func (*SplitPolicy_FixedRangePolicy) isSplitPolicy_Policy() {}

func (*SplitPolicy_BandwidthPolicy) isSplitPolicy_Policy() {}

func (m *SplitPolicy) GetPolicy() isSplitPolicy_Policy {
	if m != nil {
		return m.Policy
	}
	return nil
}

func (m *SplitPolicy) GetFixedRangePolicy() *FixedRangeSplitPolicy {
	if x, ok := m.GetPolicy().(*SplitPolicy_FixedRangePolicy); ok {
		return x.FixedRangePolicy
	}
	return nil
}

func (m *SplitPolicy) GetBandwidthPolicy() *BandwidthBasedSplitPolicy {
	if x, ok := m.GetPolicy().(*SplitPolicy_BandwidthPolicy); ok {
		return x.BandwidthPolicy
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SplitPolicy) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SplitPolicy_FixedRangePolicy)(nil),
		(*SplitPolicy_BandwidthPolicy)(nil),
	}
}

type SizeBasedSegmentRollingPolicy struct {
	MaxSegmentSize       int64    `protobuf:"varint,1,opt,name=max_segment_size,json=maxSegmentSize,proto3" json:"max_segment_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizeBasedSegmentRollingPolicy) Reset()         { *m = SizeBasedSegmentRollingPolicy{} }
func (m *SizeBasedSegmentRollingPolicy) String() string { return proto.CompactTextString(m) }
func (*SizeBasedSegmentRollingPolicy) ProtoMessage()    {}
func (*SizeBasedSegmentRollingPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{9}
}

func (m *SizeBasedSegmentRollingPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeBasedSegmentRollingPolicy.Unmarshal(m, b)
}
func (m *SizeBasedSegmentRollingPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeBasedSegmentRollingPolicy.Marshal(b, m, deterministic)
}
func (m *SizeBasedSegmentRollingPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeBasedSegmentRollingPolicy.Merge(m, src)
}
func (m *SizeBasedSegmentRollingPolicy) XXX_Size() int {
	return xxx_messageInfo_SizeBasedSegmentRollingPolicy.Size(m)
}
func (m *SizeBasedSegmentRollingPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeBasedSegmentRollingPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_SizeBasedSegmentRollingPolicy proto.InternalMessageInfo

func (m *SizeBasedSegmentRollingPolicy) GetMaxSegmentSize() int64 {
	if m != nil {
		return m.MaxSegmentSize
	}
	return 0
}

type TimeBasedSegmentRollingPolicy struct {
	IntervalSeconds      int64    `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeBasedSegmentRollingPolicy) Reset()         { *m = TimeBasedSegmentRollingPolicy{} }
func (m *TimeBasedSegmentRollingPolicy) String() string { return proto.CompactTextString(m) }
func (*TimeBasedSegmentRollingPolicy) ProtoMessage()    {}
func (*TimeBasedSegmentRollingPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{10}
}

func (m *TimeBasedSegmentRollingPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeBasedSegmentRollingPolicy.Unmarshal(m, b)
}
func (m *TimeBasedSegmentRollingPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeBasedSegmentRollingPolicy.Marshal(b, m, deterministic)
}
func (m *TimeBasedSegmentRollingPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeBasedSegmentRollingPolicy.Merge(m, src)
}
func (m *TimeBasedSegmentRollingPolicy) XXX_Size() int {
	return xxx_messageInfo_TimeBasedSegmentRollingPolicy.Size(m)
}
func (m *TimeBasedSegmentRollingPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeBasedSegmentRollingPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_TimeBasedSegmentRollingPolicy proto.InternalMessageInfo

func (m *TimeBasedSegmentRollingPolicy) GetIntervalSeconds() int64 {
	if m != nil {
		return m.IntervalSeconds
	}
	return 0
}

type SegmentRollingPolicy struct {
	SizePolicy           *SizeBasedSegmentRollingPolicy `protobuf:"bytes,1,opt,name=size_policy,json=sizePolicy,proto3" json:"size_policy,omitempty"`
	TimePolicy           *TimeBasedSegmentRollingPolicy `protobuf:"bytes,2,opt,name=time_policy,json=timePolicy,proto3" json:"time_policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *SegmentRollingPolicy) Reset()         { *m = SegmentRollingPolicy{} }
func (m *SegmentRollingPolicy) String() string { return proto.CompactTextString(m) }
func (*SegmentRollingPolicy) ProtoMessage()    {}
func (*SegmentRollingPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{11}
}

func (m *SegmentRollingPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentRollingPolicy.Unmarshal(m, b)
}
func (m *SegmentRollingPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentRollingPolicy.Marshal(b, m, deterministic)
}
func (m *SegmentRollingPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentRollingPolicy.Merge(m, src)
}
func (m *SegmentRollingPolicy) XXX_Size() int {
	return xxx_messageInfo_SegmentRollingPolicy.Size(m)
}
func (m *SegmentRollingPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentRollingPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentRollingPolicy proto.InternalMessageInfo

func (m *SegmentRollingPolicy) GetSizePolicy() *SizeBasedSegmentRollingPolicy {
	if m != nil {
		return m.SizePolicy
	}
	return nil
}

func (m *SegmentRollingPolicy) GetTimePolicy() *TimeBasedSegmentRollingPolicy {
	if m != nil {
		return m.TimePolicy
	}
	return nil
}

type TimeBasedRetentionPolicy struct {
	RetentionMinutes     int64    `protobuf:"varint,1,opt,name=retention_minutes,json=retentionMinutes,proto3" json:"retention_minutes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeBasedRetentionPolicy) Reset()         { *m = TimeBasedRetentionPolicy{} }
func (m *TimeBasedRetentionPolicy) String() string { return proto.CompactTextString(m) }
func (*TimeBasedRetentionPolicy) ProtoMessage()    {}
func (*TimeBasedRetentionPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{12}
}

func (m *TimeBasedRetentionPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeBasedRetentionPolicy.Unmarshal(m, b)
}
func (m *TimeBasedRetentionPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeBasedRetentionPolicy.Marshal(b, m, deterministic)
}
func (m *TimeBasedRetentionPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeBasedRetentionPolicy.Merge(m, src)
}
func (m *TimeBasedRetentionPolicy) XXX_Size() int {
	return xxx_messageInfo_TimeBasedRetentionPolicy.Size(m)
}
func (m *TimeBasedRetentionPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeBasedRetentionPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_TimeBasedRetentionPolicy proto.InternalMessageInfo

func (m *TimeBasedRetentionPolicy) GetRetentionMinutes() int64 {
	if m != nil {
		return m.RetentionMinutes
	}
	return 0
}

type RetentionPolicy struct {
	TimePolicy           *TimeBasedRetentionPolicy `protobuf:"bytes,1,opt,name=time_policy,json=timePolicy,proto3" json:"time_policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RetentionPolicy) Reset()         { *m = RetentionPolicy{} }
func (m *RetentionPolicy) String() string { return proto.CompactTextString(m) }
func (*RetentionPolicy) ProtoMessage()    {}
func (*RetentionPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{13}
}

func (m *RetentionPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetentionPolicy.Unmarshal(m, b)
}
func (m *RetentionPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetentionPolicy.Marshal(b, m, deterministic)
}
func (m *RetentionPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetentionPolicy.Merge(m, src)
}
func (m *RetentionPolicy) XXX_Size() int {
	return xxx_messageInfo_RetentionPolicy.Size(m)
}
func (m *RetentionPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_RetentionPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_RetentionPolicy proto.InternalMessageInfo

func (m *RetentionPolicy) GetTimePolicy() *TimeBasedRetentionPolicy {
	if m != nil {
		return m.TimePolicy
	}
	return nil
}

type StreamConfiguration struct {
	KeyType              RangeKeyType          `protobuf:"varint,1,opt,name=key_type,json=keyType,proto3,enum=bookkeeper.proto.stream.RangeKeyType" json:"key_type,omitempty"`
	MinNumRanges         int32                 `protobuf:"varint,2,opt,name=min_num_ranges,json=minNumRanges,proto3" json:"min_num_ranges,omitempty"`
	InitialNumRanges     int32                 `protobuf:"varint,3,opt,name=initial_num_ranges,json=initialNumRanges,proto3" json:"initial_num_ranges,omitempty"`
	SplitPolicy          *SplitPolicy          `protobuf:"bytes,4,opt,name=split_policy,json=splitPolicy,proto3" json:"split_policy,omitempty"`
	RollingPolicy        *SegmentRollingPolicy `protobuf:"bytes,5,opt,name=rolling_policy,json=rollingPolicy,proto3" json:"rolling_policy,omitempty"`
	RetentionPolicy      *RetentionPolicy      `protobuf:"bytes,6,opt,name=retention_policy,json=retentionPolicy,proto3" json:"retention_policy,omitempty"`
	StorageType          StorageType           `protobuf:"varint,7,opt,name=storage_type,json=storageType,proto3,enum=bookkeeper.proto.stream.StorageType" json:"storage_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StreamConfiguration) Reset()         { *m = StreamConfiguration{} }
func (m *StreamConfiguration) String() string { return proto.CompactTextString(m) }
func (*StreamConfiguration) ProtoMessage()    {}
func (*StreamConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{14}
}

func (m *StreamConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamConfiguration.Unmarshal(m, b)
}
func (m *StreamConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamConfiguration.Marshal(b, m, deterministic)
}
func (m *StreamConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamConfiguration.Merge(m, src)
}
func (m *StreamConfiguration) XXX_Size() int {
	return xxx_messageInfo_StreamConfiguration.Size(m)
}
func (m *StreamConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_StreamConfiguration proto.InternalMessageInfo

func (m *StreamConfiguration) GetKeyType() RangeKeyType {
	if m != nil {
		return m.KeyType
	}
	return RangeKeyType_NULL
}

func (m *StreamConfiguration) GetMinNumRanges() int32 {
	if m != nil {
		return m.MinNumRanges
	}
	return 0
}

func (m *StreamConfiguration) GetInitialNumRanges() int32 {
	if m != nil {
		return m.InitialNumRanges
	}
	return 0
}

func (m *StreamConfiguration) GetSplitPolicy() *SplitPolicy {
	if m != nil {
		return m.SplitPolicy
	}
	return nil
}

func (m *StreamConfiguration) GetRollingPolicy() *SegmentRollingPolicy {
	if m != nil {
		return m.RollingPolicy
	}
	return nil
}

func (m *StreamConfiguration) GetRetentionPolicy() *RetentionPolicy {
	if m != nil {
		return m.RetentionPolicy
	}
	return nil
}

func (m *StreamConfiguration) GetStorageType() StorageType {
	if m != nil {
		return m.StorageType
	}
	return StorageType_STREAM
}

type StreamProperties struct {
	StreamId             int64                `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StorageContainerId   int64                `protobuf:"varint,2,opt,name=storage_container_id,json=storageContainerId,proto3" json:"storage_container_id,omitempty"`
	StreamName           string               `protobuf:"bytes,3,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	StreamConf           *StreamConfiguration `protobuf:"bytes,4,opt,name=stream_conf,json=streamConf,proto3" json:"stream_conf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StreamProperties) Reset()         { *m = StreamProperties{} }
func (m *StreamProperties) String() string { return proto.CompactTextString(m) }
func (*StreamProperties) ProtoMessage()    {}
func (*StreamProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{15}
}

func (m *StreamProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamProperties.Unmarshal(m, b)
}
func (m *StreamProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamProperties.Marshal(b, m, deterministic)
}
func (m *StreamProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamProperties.Merge(m, src)
}
func (m *StreamProperties) XXX_Size() int {
	return xxx_messageInfo_StreamProperties.Size(m)
}
func (m *StreamProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamProperties.DiscardUnknown(m)
}

var xxx_messageInfo_StreamProperties proto.InternalMessageInfo

func (m *StreamProperties) GetStreamId() int64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *StreamProperties) GetStorageContainerId() int64 {
	if m != nil {
		return m.StorageContainerId
	}
	return 0
}

func (m *StreamProperties) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

func (m *StreamProperties) GetStreamConf() *StreamConfiguration {
	if m != nil {
		return m.StreamConf
	}
	return nil
}

type StreamName struct {
	NamespaceName        string   `protobuf:"bytes,1,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
	StreamName           string   `protobuf:"bytes,2,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamName) Reset()         { *m = StreamName{} }
func (m *StreamName) String() string { return proto.CompactTextString(m) }
func (*StreamName) ProtoMessage()    {}
func (*StreamName) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{16}
}

func (m *StreamName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamName.Unmarshal(m, b)
}
func (m *StreamName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamName.Marshal(b, m, deterministic)
}
func (m *StreamName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamName.Merge(m, src)
}
func (m *StreamName) XXX_Size() int {
	return xxx_messageInfo_StreamName.Size(m)
}
func (m *StreamName) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamName.DiscardUnknown(m)
}

var xxx_messageInfo_StreamName proto.InternalMessageInfo

func (m *StreamName) GetNamespaceName() string {
	if m != nil {
		return m.NamespaceName
	}
	return ""
}

func (m *StreamName) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

type StreamMetadata struct {
	// stream properties
	Props *StreamProperties `protobuf:"bytes,1,opt,name=props,proto3" json:"props,omitempty"`
	// stream lifecycle state
	LifecycleState StreamMetadata_LifecycleState `protobuf:"varint,2,opt,name=lifecycle_state,json=lifecycleState,proto3,enum=bookkeeper.proto.stream.StreamMetadata_LifecycleState" json:"lifecycle_state,omitempty"`
	// stream serving state
	ServingState StreamMetadata_ServingState `protobuf:"varint,3,opt,name=serving_state,json=servingState,proto3,enum=bookkeeper.proto.stream.StreamMetadata_ServingState" json:"serving_state,omitempty"`
	// time
	CTime uint64 `protobuf:"varint,4,opt,name=c_time,json=cTime,proto3" json:"c_time,omitempty"`
	MTime uint64 `protobuf:"varint,5,opt,name=m_time,json=mTime,proto3" json:"m_time,omitempty"`
	// ranges
	NextRangeId uint64 `protobuf:"varint,100,opt,name=next_range_id,json=nextRangeId,proto3" json:"next_range_id,omitempty"`
	// current active ranges
	CurrentRanges        []uint64 `protobuf:"varint,101,rep,packed,name=current_ranges,json=currentRanges,proto3" json:"current_ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMetadata) Reset()         { *m = StreamMetadata{} }
func (m *StreamMetadata) String() string { return proto.CompactTextString(m) }
func (*StreamMetadata) ProtoMessage()    {}
func (*StreamMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{17}
}

func (m *StreamMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMetadata.Unmarshal(m, b)
}
func (m *StreamMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMetadata.Marshal(b, m, deterministic)
}
func (m *StreamMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMetadata.Merge(m, src)
}
func (m *StreamMetadata) XXX_Size() int {
	return xxx_messageInfo_StreamMetadata.Size(m)
}
func (m *StreamMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMetadata proto.InternalMessageInfo

func (m *StreamMetadata) GetProps() *StreamProperties {
	if m != nil {
		return m.Props
	}
	return nil
}

func (m *StreamMetadata) GetLifecycleState() StreamMetadata_LifecycleState {
	if m != nil {
		return m.LifecycleState
	}
	return StreamMetadata_UNINIT
}

func (m *StreamMetadata) GetServingState() StreamMetadata_ServingState {
	if m != nil {
		return m.ServingState
	}
	return StreamMetadata_WRITABLE
}

func (m *StreamMetadata) GetCTime() uint64 {
	if m != nil {
		return m.CTime
	}
	return 0
}

func (m *StreamMetadata) GetMTime() uint64 {
	if m != nil {
		return m.MTime
	}
	return 0
}

func (m *StreamMetadata) GetNextRangeId() uint64 {
	if m != nil {
		return m.NextRangeId
	}
	return 0
}

func (m *StreamMetadata) GetCurrentRanges() []uint64 {
	if m != nil {
		return m.CurrentRanges
	}
	return nil
}

// user requested
type NamespaceConfiguration struct {
	DefaultStreamConf    *StreamConfiguration `protobuf:"bytes,1,opt,name=default_stream_conf,json=defaultStreamConf,proto3" json:"default_stream_conf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NamespaceConfiguration) Reset()         { *m = NamespaceConfiguration{} }
func (m *NamespaceConfiguration) String() string { return proto.CompactTextString(m) }
func (*NamespaceConfiguration) ProtoMessage()    {}
func (*NamespaceConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{18}
}

func (m *NamespaceConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceConfiguration.Unmarshal(m, b)
}
func (m *NamespaceConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceConfiguration.Marshal(b, m, deterministic)
}
func (m *NamespaceConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceConfiguration.Merge(m, src)
}
func (m *NamespaceConfiguration) XXX_Size() int {
	return xxx_messageInfo_NamespaceConfiguration.Size(m)
}
func (m *NamespaceConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceConfiguration proto.InternalMessageInfo

func (m *NamespaceConfiguration) GetDefaultStreamConf() *StreamConfiguration {
	if m != nil {
		return m.DefaultStreamConf
	}
	return nil
}

// public metadata for a namespace
type NamespaceProperties struct {
	NamespaceId          int64                `protobuf:"varint,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	NamespaceName        string               `protobuf:"bytes,2,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
	DefaultStreamConf    *StreamConfiguration `protobuf:"bytes,3,opt,name=default_stream_conf,json=defaultStreamConf,proto3" json:"default_stream_conf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NamespaceProperties) Reset()         { *m = NamespaceProperties{} }
func (m *NamespaceProperties) String() string { return proto.CompactTextString(m) }
func (*NamespaceProperties) ProtoMessage()    {}
func (*NamespaceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{19}
}

func (m *NamespaceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceProperties.Unmarshal(m, b)
}
func (m *NamespaceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceProperties.Marshal(b, m, deterministic)
}
func (m *NamespaceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceProperties.Merge(m, src)
}
func (m *NamespaceProperties) XXX_Size() int {
	return xxx_messageInfo_NamespaceProperties.Size(m)
}
func (m *NamespaceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceProperties proto.InternalMessageInfo

func (m *NamespaceProperties) GetNamespaceId() int64 {
	if m != nil {
		return m.NamespaceId
	}
	return 0
}

func (m *NamespaceProperties) GetNamespaceName() string {
	if m != nil {
		return m.NamespaceName
	}
	return ""
}

func (m *NamespaceProperties) GetDefaultStreamConf() *StreamConfiguration {
	if m != nil {
		return m.DefaultStreamConf
	}
	return nil
}

// the whole metadata for a namespace (including both public and private)
type NamespaceMetadata struct {
	Props                *NamespaceProperties `protobuf:"bytes,1,opt,name=props,proto3" json:"props,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NamespaceMetadata) Reset()         { *m = NamespaceMetadata{} }
func (m *NamespaceMetadata) String() string { return proto.CompactTextString(m) }
func (*NamespaceMetadata) ProtoMessage()    {}
func (*NamespaceMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{20}
}

func (m *NamespaceMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceMetadata.Unmarshal(m, b)
}
func (m *NamespaceMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceMetadata.Marshal(b, m, deterministic)
}
func (m *NamespaceMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceMetadata.Merge(m, src)
}
func (m *NamespaceMetadata) XXX_Size() int {
	return xxx_messageInfo_NamespaceMetadata.Size(m)
}
func (m *NamespaceMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceMetadata proto.InternalMessageInfo

func (m *NamespaceMetadata) GetProps() *NamespaceProperties {
	if m != nil {
		return m.Props
	}
	return nil
}

func init() {
	proto.RegisterEnum("bookkeeper.proto.stream.RangeState", RangeState_name, RangeState_value)
	proto.RegisterEnum("bookkeeper.proto.stream.RangeKeyType", RangeKeyType_name, RangeKeyType_value)
	proto.RegisterEnum("bookkeeper.proto.stream.StorageType", StorageType_name, StorageType_value)
	proto.RegisterEnum("bookkeeper.proto.stream.SplitPolicyType", SplitPolicyType_name, SplitPolicyType_value)
	proto.RegisterEnum("bookkeeper.proto.stream.StreamMetadata_LifecycleState", StreamMetadata_LifecycleState_name, StreamMetadata_LifecycleState_value)
	proto.RegisterEnum("bookkeeper.proto.stream.StreamMetadata_ServingState", StreamMetadata_ServingState_name, StreamMetadata_ServingState_value)
	proto.RegisterType((*RangeId)(nil), "bookkeeper.proto.stream.RangeId")
	proto.RegisterType((*KeyRange)(nil), "bookkeeper.proto.stream.KeyRange")
	proto.RegisterType((*RangeProperties)(nil), "bookkeeper.proto.stream.RangeProperties")
	proto.RegisterType((*RangeMetadata)(nil), "bookkeeper.proto.stream.RangeMetadata")
	proto.RegisterType((*ParentRanges)(nil), "bookkeeper.proto.stream.ParentRanges")
	proto.RegisterType((*ParentRangesList)(nil), "bookkeeper.proto.stream.ParentRangesList")
	proto.RegisterType((*FixedRangeSplitPolicy)(nil), "bookkeeper.proto.stream.FixedRangeSplitPolicy")
	proto.RegisterType((*BandwidthBasedSplitPolicy)(nil), "bookkeeper.proto.stream.BandwidthBasedSplitPolicy")
	proto.RegisterType((*SplitPolicy)(nil), "bookkeeper.proto.stream.SplitPolicy")
	proto.RegisterType((*SizeBasedSegmentRollingPolicy)(nil), "bookkeeper.proto.stream.SizeBasedSegmentRollingPolicy")
	proto.RegisterType((*TimeBasedSegmentRollingPolicy)(nil), "bookkeeper.proto.stream.TimeBasedSegmentRollingPolicy")
	proto.RegisterType((*SegmentRollingPolicy)(nil), "bookkeeper.proto.stream.SegmentRollingPolicy")
	proto.RegisterType((*TimeBasedRetentionPolicy)(nil), "bookkeeper.proto.stream.TimeBasedRetentionPolicy")
	proto.RegisterType((*RetentionPolicy)(nil), "bookkeeper.proto.stream.RetentionPolicy")
	proto.RegisterType((*StreamConfiguration)(nil), "bookkeeper.proto.stream.StreamConfiguration")
	proto.RegisterType((*StreamProperties)(nil), "bookkeeper.proto.stream.StreamProperties")
	proto.RegisterType((*StreamName)(nil), "bookkeeper.proto.stream.StreamName")
	proto.RegisterType((*StreamMetadata)(nil), "bookkeeper.proto.stream.StreamMetadata")
	proto.RegisterType((*NamespaceConfiguration)(nil), "bookkeeper.proto.stream.NamespaceConfiguration")
	proto.RegisterType((*NamespaceProperties)(nil), "bookkeeper.proto.stream.NamespaceProperties")
	proto.RegisterType((*NamespaceMetadata)(nil), "bookkeeper.proto.stream.NamespaceMetadata")
}

func init() { proto.RegisterFile("stream.proto", fileDescriptor_bb17ef3f514bfe54) }

var fileDescriptor_bb17ef3f514bfe54 = []byte{
	// 1486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5b, 0x6f, 0x1b, 0xc5,
	0x17, 0xcf, 0xfa, 0x92, 0x38, 0xc7, 0x97, 0x6c, 0x26, 0xcd, 0xff, 0xef, 0x16, 0x55, 0x84, 0xa5,
	0x91, 0xd2, 0xb4, 0x71, 0x20, 0xa0, 0x4a, 0x20, 0x04, 0xd8, 0x89, 0x13, 0x9b, 0x26, 0x26, 0x5a,
	0xbb, 0x0d, 0x45, 0x15, 0xab, 0xcd, 0xee, 0xd8, 0x1e, 0xc5, 0x7b, 0xd1, 0xcc, 0x3a, 0xc4, 0x7d,
	0xe6, 0x33, 0xf0, 0xc4, 0x33, 0xdf, 0x82, 0x77, 0x5e, 0xf9, 0x16, 0x7c, 0x05, 0xde, 0xd0, 0xcc,
	0xec, 0xcd, 0x6e, 0xec, 0x54, 0xa8, 0x6f, 0x9e, 0x73, 0x7e, 0xe7, 0x37, 0xe7, 0x3a, 0x7b, 0x0c,
	0x25, 0x16, 0x50, 0x6c, 0x3a, 0x35, 0x9f, 0x7a, 0x81, 0x87, 0xfe, 0x7f, 0xe9, 0x79, 0x57, 0x57,
	0x18, 0xfb, 0x98, 0x4a, 0x49, 0x4d, 0xaa, 0xb5, 0x97, 0xb0, 0xa2, 0x9b, 0xee, 0x00, 0xb7, 0x6d,
	0xb4, 0x01, 0x79, 0x66, 0x19, 0xc4, 0xae, 0x2a, 0x5b, 0xca, 0x4e, 0x56, 0xcf, 0x31, 0xab, 0x6d,
	0xa3, 0x0f, 0x60, 0x55, 0x22, 0xb9, 0x22, 0x23, 0x14, 0x05, 0x29, 0x68, 0xdb, 0xe8, 0x3e, 0x14,
	0x28, 0x37, 0xe6, 0xba, 0xac, 0xd0, 0xad, 0x50, 0x49, 0xa6, 0xe9, 0x50, 0x78, 0x8e, 0x27, 0x82,
	0x1a, 0x3d, 0x82, 0x0a, 0x0b, 0x4c, 0x1a, 0x18, 0x43, 0x93, 0x0d, 0x8d, 0x2b, 0x3c, 0x09, 0x6f,
	0x28, 0x09, 0x69, 0xcb, 0x64, 0xc3, 0xe7, 0x78, 0x82, 0xb6, 0xa0, 0x84, 0x5d, 0x3b, 0xc1, 0xc8,
	0xcb, 0x00, 0xbb, 0x76, 0x88, 0xd0, 0x7e, 0x57, 0x60, 0x4d, 0x30, 0x9e, 0x53, 0xcf, 0xc7, 0x34,
	0x20, 0x98, 0xbd, 0x2f, 0xee, 0x05, 0xa1, 0xa0, 0x4f, 0xe0, 0x1e, 0x0b, 0x3c, 0x6a, 0x0e, 0xb0,
	0x61, 0x79, 0x6e, 0x60, 0x12, 0x17, 0x53, 0x0e, 0xcb, 0x09, 0x18, 0x0a, 0x75, 0x87, 0x91, 0xaa,
	0x6d, 0x6b, 0xbf, 0x65, 0xa0, 0x2c, 0x1c, 0x3d, 0xc3, 0x81, 0x69, 0x9b, 0x81, 0x89, 0xbe, 0x86,
	0xbc, 0x4f, 0x3d, 0x9f, 0x09, 0xef, 0x8a, 0x07, 0x3b, 0xb5, 0x39, 0xf5, 0xa8, 0xcd, 0xc4, 0xa7,
	0x4b, 0x33, 0xf4, 0x00, 0x0a, 0x14, 0x5f, 0x13, 0x46, 0x3c, 0x37, 0xaa, 0x42, 0x74, 0x46, 0x5f,
	0x40, 0x9e, 0x05, 0x66, 0x80, 0x85, 0xdf, 0x95, 0x83, 0x8f, 0x17, 0x73, 0x77, 0x39, 0x54, 0x97,
	0x16, 0xe8, 0x43, 0x28, 0x5a, 0x14, 0x9b, 0x01, 0x36, 0x02, 0xe2, 0xe0, 0x2a, 0xc8, 0xb4, 0x48,
	0x51, 0x8f, 0x38, 0x18, 0x3d, 0x04, 0xe8, 0x63, 0xd7, 0x0a, 0xf5, 0x45, 0xa1, 0x5f, 0x15, 0x12,
	0xa1, 0x7e, 0x00, 0x05, 0x6b, 0x48, 0x46, 0x36, 0xc5, 0x6e, 0xf5, 0xde, 0x56, 0x96, 0xbb, 0x15,
	0x9d, 0x51, 0x15, 0x56, 0x7c, 0x93, 0x62, 0x37, 0x60, 0xd5, 0x4d, 0xa1, 0x8a, 0x8e, 0x5a, 0x17,
	0x4a, 0xe7, 0xe2, 0xa7, 0x70, 0x88, 0x4d, 0xe5, 0x5e, 0x99, 0xce, 0xfd, 0x0e, 0xa8, 0xd2, 0xca,
	0x88, 0x10, 0xac, 0x9a, 0x11, 0x6c, 0x15, 0x3f, 0xa1, 0x68, 0xdb, 0x4c, 0x7b, 0x0d, 0x6a, 0x9a,
	0xf4, 0x94, 0xb0, 0x00, 0xb5, 0xa0, 0x24, 0xdc, 0x91, 0xc6, 0x3c, 0xf9, 0xd9, 0x9d, 0xe2, 0xc1,
	0xf6, 0xdc, 0x04, 0xa5, 0x09, 0xf4, 0xa2, 0x30, 0x95, 0x07, 0xed, 0x19, 0x6c, 0x1e, 0x93, 0x1b,
	0x2c, 0x8f, 0x5d, 0x7f, 0x44, 0x82, 0x73, 0x6f, 0x44, 0xac, 0x09, 0x4f, 0x90, 0x3b, 0x76, 0x92,
	0x0b, 0x94, 0x9d, 0xbc, 0xbe, 0xea, 0x8e, 0x9d, 0xd0, 0xee, 0x1f, 0x05, 0xee, 0x37, 0x4c, 0xd7,
	0xfe, 0x99, 0xd8, 0xc1, 0xb0, 0x61, 0x32, 0x6c, 0xa7, 0x8d, 0x1f, 0xc3, 0xba, 0x63, 0xde, 0x18,
	0x94, 0x17, 0x80, 0xb8, 0xc6, 0xe5, 0x24, 0x88, 0x39, 0x2a, 0x8e, 0x79, 0xa3, 0x9b, 0x01, 0x6e,
	0xbb, 0x0d, 0x2e, 0x15, 0x50, 0xe2, 0xce, 0x40, 0x33, 0x21, 0x94, 0xb8, 0x69, 0xe8, 0x1e, 0x6c,
	0xa4, 0x59, 0x29, 0xb6, 0x3c, 0x6a, 0x33, 0xd1, 0x1d, 0x79, 0x5d, 0x8d, 0x79, 0x75, 0x29, 0x17,
	0xf0, 0x14, 0x73, 0x04, 0xcf, 0x85, 0xf0, 0x88, 0x3b, 0x82, 0xef, 0x00, 0xa7, 0x30, 0x18, 0x0f,
	0xc3, 0xe8, 0x9b, 0x56, 0xe0, 0xd1, 0x6a, 0x3e, 0x76, 0x59, 0x44, 0x77, 0x2c, 0xa4, 0xda, 0xaf,
	0x19, 0x28, 0xa6, 0xa3, 0xfd, 0x0a, 0x72, 0xc1, 0xc4, 0xc7, 0x22, 0xc0, 0xca, 0x82, 0x11, 0x48,
	0xd9, 0xf4, 0x26, 0x3e, 0xd6, 0x85, 0x15, 0xfa, 0x09, 0x50, 0x9f, 0x57, 0x20, 0x6c, 0x04, 0x5f,
	0xe8, 0x45, 0x06, 0x8a, 0x07, 0xb5, 0xb9, 0x5c, 0xb7, 0x16, 0xad, 0xb5, 0xa4, 0xab, 0xfd, 0x58,
	0x11, 0x7a, 0x67, 0x80, 0x7a, 0x19, 0x15, 0x2a, 0x62, 0xcf, 0x0a, 0xf6, 0x83, 0xb9, 0xec, 0x73,
	0x2b, 0xdb, 0x5a, 0xd2, 0xd7, 0x62, 0x36, 0x29, 0x6a, 0x14, 0x60, 0x59, 0xd2, 0x6a, 0x6d, 0x78,
	0xd8, 0x25, 0x6f, 0xb0, 0x34, 0xc2, 0x03, 0x87, 0xf7, 0x9c, 0x37, 0x1a, 0x11, 0x77, 0x10, 0xfa,
	0x12, 0xe5, 0x58, 0xea, 0x0c, 0x46, 0xde, 0xe0, 0x70, 0x30, 0x44, 0x8e, 0xa5, 0x98, 0x53, 0x68,
	0xdf, 0xc1, 0x43, 0x3e, 0x88, 0xf3, 0xa9, 0x1e, 0x83, 0x4a, 0xdc, 0x00, 0xd3, 0x6b, 0x73, 0x64,
	0x30, 0x6c, 0x79, 0xae, 0xcd, 0x42, 0xaa, 0xb5, 0x48, 0xde, 0x95, 0x62, 0xed, 0x4f, 0x05, 0xee,
	0xdd, 0xca, 0x71, 0x01, 0x45, 0xee, 0x42, 0x94, 0x15, 0xf9, 0x84, 0x3d, 0x9b, 0x5f, 0xbf, 0x45,
	0xb1, 0xe9, 0xc0, 0xa9, 0x12, 0x62, 0xfe, 0xae, 0x4c, 0x17, 0x73, 0x3e, 0xf1, 0xc2, 0x48, 0x75,
	0xe0, 0x54, 0xf2, 0xb7, 0x76, 0x02, 0xd5, 0x18, 0xac, 0xe3, 0x00, 0xbb, 0x01, 0xf1, 0xdc, 0xf0,
	0xd2, 0x27, 0xb0, 0x4e, 0x23, 0x91, 0xe1, 0x10, 0x77, 0x1c, 0x0d, 0x5d, 0x56, 0x57, 0x63, 0xc5,
	0x99, 0x94, 0x6b, 0x18, 0xd6, 0x66, 0xed, 0xf5, 0x69, 0xa7, 0x65, 0x36, 0x3e, 0xbd, 0xdb, 0xe9,
	0x19, 0x9e, 0x29, 0x7f, 0xff, 0xce, 0xc2, 0x46, 0x57, 0xe0, 0x0f, 0x3d, 0xb7, 0x4f, 0x06, 0x63,
	0x6a, 0x72, 0x24, 0xfa, 0x16, 0x0a, 0x57, 0x78, 0x62, 0xa4, 0xc6, 0x66, 0x7b, 0xf1, 0xeb, 0xfe,
	0x1c, 0xcb, 0x99, 0x59, 0xb9, 0x92, 0x3f, 0xf8, 0xf7, 0x91, 0x4f, 0x77, 0xea, 0x8d, 0x92, 0x8f,
	0x46, 0xc9, 0x21, 0x6e, 0x27, 0x7a, 0xa6, 0xd0, 0x53, 0x40, 0xc4, 0x25, 0x01, 0x31, 0x47, 0x69,
	0x64, 0xf8, 0x62, 0x84, 0x9a, 0x04, 0x7d, 0x02, 0x25, 0x39, 0xfe, 0x61, 0x0a, 0x72, 0x22, 0x05,
	0x8f, 0xde, 0x65, 0xa0, 0xf5, 0x22, 0x4b, 0xbd, 0x08, 0x3d, 0xa8, 0x50, 0x59, 0xc3, 0x88, 0x2a,
	0x2f, 0xa8, 0xf6, 0xe6, 0x53, 0xdd, 0x56, 0xf9, 0x32, 0x9d, 0x6a, 0xd7, 0x2e, 0x24, 0x75, 0x8c,
	0x78, 0x97, 0xef, 0xfa, 0xec, 0xce, 0x14, 0x67, 0x8d, 0xce, 0x54, 0x9d, 0xc7, 0x1c, 0x2e, 0x01,
	0xa2, 0x1a, 0x2b, 0xa2, 0x1a, 0x0b, 0x62, 0x96, 0x60, 0x51, 0x8c, 0x22, 0x4b, 0x0e, 0xda, 0x5f,
	0x0a, 0xa8, 0xb2, 0xd4, 0xa9, 0x2d, 0x66, 0x6a, 0xcb, 0x52, 0x66, 0xb6, 0xac, 0x79, 0xfb, 0x47,
	0x66, 0xde, 0xfe, 0xc1, 0x3f, 0xeb, 0x21, 0x9d, 0x6b, 0x3a, 0x72, 0x2f, 0x58, 0xd5, 0x41, 0x8a,
	0x3a, 0xa6, 0x83, 0xd1, 0x59, 0x0c, 0xb0, 0x3c, 0xb7, 0x1f, 0x16, 0xf0, 0xe9, 0x82, 0x60, 0xde,
	0x6a, 0xcd, 0x88, 0x8e, 0x0b, 0xb5, 0x1e, 0x40, 0x37, 0x21, 0xdf, 0x86, 0x0a, 0xbf, 0x96, 0xf9,
	0xa6, 0x85, 0xa5, 0x03, 0x8a, 0x70, 0xa0, 0x1c, 0x4b, 0x05, 0x6c, 0xc6, 0xc9, 0xcc, 0xac, 0x93,
	0xda, 0x2f, 0x39, 0xa8, 0x48, 0xda, 0x78, 0x8d, 0xfa, 0x66, 0x7a, 0x8d, 0x7a, 0x7c, 0x87, 0xc7,
	0x6f, 0xef, 0x51, 0x06, 0xac, 0x8d, 0x48, 0x1f, 0x5b, 0x13, 0x6b, 0x84, 0x0d, 0xb9, 0x35, 0x65,
	0x44, 0x25, 0x9f, 0xdd, 0x41, 0x15, 0xb9, 0x50, 0x3b, 0x8d, 0xcc, 0xe5, 0x22, 0x55, 0x19, 0x4d,
	0x9d, 0xd1, 0x2b, 0x28, 0x33, 0x4c, 0xaf, 0x79, 0x4b, 0xa7, 0x97, 0xb2, 0xcf, 0xdf, 0x95, 0xbe,
	0x2b, 0x8d, 0x25, 0x79, 0x89, 0xa5, 0x4e, 0x68, 0x13, 0x96, 0x2d, 0xb9, 0x87, 0xf1, 0x7a, 0xe5,
	0xf4, 0xbc, 0x25, 0x76, 0xb0, 0x4d, 0x58, 0x76, 0xa4, 0x38, 0x2f, 0xc5, 0x8e, 0x10, 0x6b, 0x50,
	0x76, 0xf1, 0x4d, 0xb2, 0x37, 0x55, 0x6d, 0xa1, 0x2d, 0x72, 0x61, 0xb4, 0xf1, 0x6f, 0x43, 0xc5,
	0x1a, 0xd3, 0x64, 0xbd, 0x62, 0x55, 0xbc, 0x95, 0xdd, 0xc9, 0xe9, 0xe5, 0x50, 0x1a, 0x2e, 0x31,
	0xe7, 0x50, 0x99, 0x8e, 0x1a, 0x01, 0x2c, 0xbf, 0xe8, 0xb4, 0x3b, 0xed, 0x9e, 0xba, 0x84, 0x4a,
	0x50, 0x38, 0xd4, 0x9b, 0xf5, 0x5e, 0xbb, 0x73, 0xa2, 0x2a, 0xa8, 0x08, 0x2b, 0xe2, 0xd4, 0x3c,
	0x52, 0x33, 0xfc, 0x70, 0xdc, 0xec, 0x1c, 0x72, 0x4d, 0x96, 0xdb, 0xf0, 0x43, 0xf3, 0x48, 0xcd,
	0x69, 0xbb, 0x50, 0x4a, 0x07, 0xca, 0x39, 0x2e, 0xf4, 0x76, 0xaf, 0xde, 0x38, 0x6d, 0x4a, 0x46,
	0xbd, 0x59, 0x3f, 0xfa, 0xbe, 0x73, 0xfa, 0x4a, 0x55, 0xb4, 0x6b, 0xf8, 0x5f, 0x27, 0x6a, 0x9c,
	0xe9, 0xd7, 0xf1, 0x35, 0x6c, 0xd8, 0xb8, 0x6f, 0x8e, 0x47, 0x81, 0x91, 0xee, 0x66, 0xe5, 0x3f,
	0x74, 0xf3, 0x7a, 0x48, 0x94, 0xe8, 0xb4, 0x3f, 0x14, 0xd8, 0x88, 0x2f, 0x4e, 0xcd, 0xea, 0x47,
	0x50, 0x4a, 0xda, 0x3b, 0x1e, 0xd7, 0x62, 0x2c, 0x93, 0x79, 0x9d, 0x99, 0x80, 0xcc, 0x6d, 0x13,
	0x30, 0xc7, 0xff, 0xec, 0xfb, 0xf1, 0xff, 0x02, 0xd6, 0x63, 0xf7, 0xe3, 0x01, 0x6a, 0x4c, 0x0f,
	0xd0, 0xfc, 0x4b, 0x6e, 0x89, 0x3c, 0x9c, 0xa1, 0xdd, 0x43, 0x80, 0xe4, 0x9f, 0x04, 0x52, 0xa1,
	0xa4, 0xd7, 0x3b, 0x27, 0x4d, 0xa3, 0x7e, 0xd8, 0x6b, 0xbf, 0xe4, 0xe5, 0x5b, 0x87, 0xb2, 0x94,
	0x44, 0xb5, 0x57, 0x12, 0x50, 0xd8, 0x01, 0x99, 0xdd, 0x27, 0x50, 0x4a, 0x7f, 0xb0, 0x50, 0x01,
	0x72, 0x9d, 0x17, 0xa7, 0xa7, 0xea, 0x12, 0xff, 0xd5, 0xaa, 0x77, 0x5b, 0xaa, 0x82, 0x56, 0x20,
	0xab, 0xd7, 0x2f, 0xd4, 0xcc, 0xee, 0x23, 0x28, 0xa6, 0xde, 0x53, 0xde, 0x49, 0xdd, 0x9e, 0xde,
	0xac, 0x9f, 0xa9, 0x4b, 0x68, 0x15, 0xf2, 0xb2, 0x6d, 0x94, 0xdd, 0x27, 0xb0, 0x36, 0xb3, 0x3a,
	0x72, 0xed, 0x71, 0xfb, 0x87, 0xe6, 0x91, 0xba, 0x84, 0xca, 0xb0, 0xda, 0xa8, 0x77, 0x8e, 0x2e,
	0xda, 0x47, 0xbd, 0x96, 0xaa, 0x34, 0x2e, 0x41, 0xf3, 0xe8, 0xa0, 0x66, 0xfa, 0xa6, 0x35, 0xc4,
	0xe9, 0x2c, 0xa4, 0xff, 0x36, 0x9f, 0x2b, 0x3f, 0x7e, 0x39, 0x20, 0xc1, 0x70, 0x7c, 0x59, 0xb3,
	0x3c, 0x67, 0xdf, 0x1f, 0x62, 0xc7, 0xc1, 0x74, 0x7f, 0xe0, 0xed, 0xf9, 0xe3, 0x11, 0x33, 0xe9,
	0x9e, 0x18, 0xf1, 0xfd, 0xc4, 0x7a, 0x5f, 0x98, 0xed, 0x4b, 0x8e, 0xcb, 0x65, 0x71, 0xfa, 0xec,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x95, 0xa8, 0xd3, 0x8b, 0x0f, 0x00, 0x00,
}
