// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

package cluster

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerAssignmentData struct {
	// assigned containers
	Containers           []int64  `protobuf:"varint,1,rep,packed,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerAssignmentData) Reset()         { *m = ServerAssignmentData{} }
func (m *ServerAssignmentData) String() string { return proto.CompactTextString(m) }
func (*ServerAssignmentData) ProtoMessage()    {}
func (*ServerAssignmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{0}
}

func (m *ServerAssignmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerAssignmentData.Unmarshal(m, b)
}
func (m *ServerAssignmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerAssignmentData.Marshal(b, m, deterministic)
}
func (m *ServerAssignmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerAssignmentData.Merge(m, src)
}
func (m *ServerAssignmentData) XXX_Size() int {
	return xxx_messageInfo_ServerAssignmentData.Size(m)
}
func (m *ServerAssignmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerAssignmentData.DiscardUnknown(m)
}

var xxx_messageInfo_ServerAssignmentData proto.InternalMessageInfo

func (m *ServerAssignmentData) GetContainers() []int64 {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ClusterAssignmentData struct {
	Servers              map[string]*ServerAssignmentData `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ClusterAssignmentData) Reset()         { *m = ClusterAssignmentData{} }
func (m *ClusterAssignmentData) String() string { return proto.CompactTextString(m) }
func (*ClusterAssignmentData) ProtoMessage()    {}
func (*ClusterAssignmentData) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{1}
}

func (m *ClusterAssignmentData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterAssignmentData.Unmarshal(m, b)
}
func (m *ClusterAssignmentData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterAssignmentData.Marshal(b, m, deterministic)
}
func (m *ClusterAssignmentData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterAssignmentData.Merge(m, src)
}
func (m *ClusterAssignmentData) XXX_Size() int {
	return xxx_messageInfo_ClusterAssignmentData.Size(m)
}
func (m *ClusterAssignmentData) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterAssignmentData.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterAssignmentData proto.InternalMessageInfo

func (m *ClusterAssignmentData) GetServers() map[string]*ServerAssignmentData {
	if m != nil {
		return m.Servers
	}
	return nil
}

type ClusterMetadata struct {
	NumStorageContainers int64    `protobuf:"varint,1,opt,name=num_storage_containers,json=numStorageContainers,proto3" json:"num_storage_containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterMetadata) Reset()         { *m = ClusterMetadata{} }
func (m *ClusterMetadata) String() string { return proto.CompactTextString(m) }
func (*ClusterMetadata) ProtoMessage()    {}
func (*ClusterMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{2}
}

func (m *ClusterMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterMetadata.Unmarshal(m, b)
}
func (m *ClusterMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterMetadata.Marshal(b, m, deterministic)
}
func (m *ClusterMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterMetadata.Merge(m, src)
}
func (m *ClusterMetadata) XXX_Size() int {
	return xxx_messageInfo_ClusterMetadata.Size(m)
}
func (m *ClusterMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterMetadata proto.InternalMessageInfo

func (m *ClusterMetadata) GetNumStorageContainers() int64 {
	if m != nil {
		return m.NumStorageContainers
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerAssignmentData)(nil), "bookkeeper.proto.cluster.ServerAssignmentData")
	proto.RegisterType((*ClusterAssignmentData)(nil), "bookkeeper.proto.cluster.ClusterAssignmentData")
	proto.RegisterMapType((map[string]*ServerAssignmentData)(nil), "bookkeeper.proto.cluster.ClusterAssignmentData.ServersEntry")
	proto.RegisterType((*ClusterMetadata)(nil), "bookkeeper.proto.cluster.ClusterMetadata")
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor_3cfb3b8ec240c376) }

var fileDescriptor_3cfb3b8ec240c376 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xd9, 0x86, 0xef, 0x13, 0xa7, 0x8a, 0x12, 0xaa, 0x04, 0x0f, 0x52, 0x7a, 0x0a, 0x42,
	0x37, 0x50, 0x45, 0x44, 0xbd, 0x68, 0x2b, 0x9e, 0x04, 0x49, 0xc1, 0x83, 0x97, 0xb2, 0x8d, 0x43,
	0x5a, 0x93, 0xdd, 0x0d, 0xbb, 0xb3, 0x85, 0xfe, 0x56, 0xff, 0x8c, 0x34, 0x49, 0x35, 0x95, 0xf6,
	0x96, 0xcc, 0xcb, 0xf3, 0xcc, 0x3b, 0x0b, 0x87, 0x49, 0xee, 0x2c, 0xa1, 0xe1, 0x85, 0xd1, 0xa4,
	0xfd, 0x60, 0xaa, 0x75, 0x96, 0x21, 0x16, 0xeb, 0x09, 0xaf, 0xf3, 0xde, 0x35, 0x74, 0xc6, 0x68,
	0x16, 0x68, 0x1e, 0xac, 0x9d, 0xa7, 0x4a, 0xa2, 0xa2, 0x91, 0x20, 0xe1, 0x9f, 0x03, 0x24, 0x5a,
	0x91, 0x98, 0x2b, 0x34, 0x36, 0x60, 0x5d, 0x2f, 0xf4, 0xe2, 0xc6, 0xa4, 0xf7, 0xc5, 0xe0, 0x64,
	0x58, 0x39, 0xfe, 0x90, 0x6f, 0xb0, 0x67, 0x4b, 0x63, 0x85, 0xb5, 0x07, 0xf7, 0x7c, 0xd7, 0x76,
	0xbe, 0xd5, 0xc0, 0xab, 0x42, 0xf6, 0x49, 0x91, 0x59, 0xc6, 0x6b, 0xd9, 0xd9, 0x27, 0x1c, 0x34,
	0x03, 0xff, 0x18, 0xbc, 0x0c, 0x97, 0x01, 0xeb, 0xb2, 0x70, 0x3f, 0x5e, 0x7d, 0xfa, 0x23, 0xf8,
	0xb7, 0x10, 0xb9, 0xc3, 0xa0, 0xd5, 0x65, 0x61, 0x7b, 0xc0, 0x77, 0xef, 0xdd, 0x76, 0x72, 0x5c,
	0xc1, 0xb7, 0xad, 0x1b, 0xd6, 0x7b, 0x86, 0xa3, 0xba, 0xda, 0x0b, 0x92, 0xf8, 0x58, 0x9d, 0x75,
	0x05, 0xa7, 0xca, 0xc9, 0x89, 0x25, 0x6d, 0x44, 0x8a, 0x93, 0x8d, 0xc7, 0x61, 0xa1, 0x17, 0x77,
	0x94, 0x93, 0xe3, 0x2a, 0x1c, 0xfe, 0x64, 0x8f, 0x19, 0x5c, 0x68, 0x93, 0x72, 0x51, 0x88, 0x64,
	0x86, 0xcd, 0x3e, 0x96, 0x0c, 0x0a, 0xb9, 0x59, 0xeb, 0x95, 0xbd, 0xdf, 0xa5, 0x73, 0x9a, 0xb9,
	0x29, 0x4f, 0xb4, 0x8c, 0x8a, 0x19, 0x4a, 0x89, 0x26, 0x4a, 0x75, 0xbf, 0x70, 0xb9, 0x15, 0xa6,
	0x6f, 0x49, 0x10, 0x46, 0xbf, 0x96, 0xa8, 0xc4, 0xa3, 0x1a, 0x9f, 0xfe, 0x2f, 0x7f, 0x2f, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x61, 0x3a, 0xab, 0x73, 0xfd, 0x01, 0x00, 0x00,
}
